export interface BackpackingDestination {
  id: string;
  title: string;
  subtitle: string;
  location: string;
  state: string;
  region: "uttarakhand" | "himachal";
  duration: string;
  bestSeason: string;
  rating: string;
  reviewCount: string;
  images: string[];
  brief: string;
  description: string;
  highlights: string[];
  price: number;
  mapImage: string;
}

export const backpackingDestinations: BackpackingDestination[] = [
  {
    id: "rishikesh",
    title: "Rishikesh Backpacking",
    subtitle: "The Yoga Capital of the World",
    location: "Rishikesh, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "3N/4D",
    bestSeason: "September - June",
    rating: "4.7",
    reviewCount: "15k+",
    images: ["https://images.unsplash.com/photo-1548013146-72479768bada?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=600&fit=crop"],
    brief: "Backpack through the world capital of yoga and adventure sports on the banks of the holy Ganges.",
    description: "Rishikesh is the ultimate backpacking destination in Uttarakhand, offering river rafting, cliff jumping, beach camping, yoga retreats, and the iconic Ganga Aarti at Triveni Ghat. Explore Beatles Ashram, Laxman Jhula, and the vibrant cafe culture.",
    highlights: ["White water rafting on the Ganges", "Ganga Aarti at Triveni Ghat", "Beach camping with bonfire", "Beatles Ashram and yoga retreats", "Cliff jumping and river swimming", "Cafe culture and budget hostels"],
    price: 2999,
    mapImage: "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&h=500&fit=crop",
  },
  {
    id: "mussoorie",
    title: "Mussoorie Backpacking",
    subtitle: "The Queen of Hills",
    location: "Mussoorie, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "2N/3D",
    bestSeason: "March - June, September - November",
    rating: "4.5",
    reviewCount: "10k+",
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=600&fit=crop"],
    brief: "Explore the colonial charm of Mussoorie with its Mall Road, waterfalls, and panoramic Himalayan views.",
    description: "Mussoorie, the Queen of Hills, is a classic backpacking destination. Walk the Mall Road, hike to Gun Hill and Lal Tibba, visit Kempty Falls, and enjoy stunning Doon Valley vistas from the ridge.",
    highlights: ["Mall Road and Ridge walks", "Gun Hill and Lal Tibba viewpoints", "Kempty Falls picnic", "Colonial architecture and Landour", "Cable car ride", "Sunset at Cloud End"],
    price: 2499,
    mapImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop",
  },
  {
    id: "kanatal",
    title: "Kanatal Backpacking",
    subtitle: "The Peaceful Hill Escape",
    location: "Kanatal, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "2N/3D",
    bestSeason: "March - June, September - December",
    rating: "4.4",
    reviewCount: "4k+",
    images: ["https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop"],
    brief: "A quiet hill station away from crowds with dense cedar forests and stunning sunset points.",
    description: "Kanatal is a serene backpacking destination near Mussoorie, known for its apple orchards, pine forests, and the famous Kodia Jungle. Perfect for campers and peace seekers.",
    highlights: ["Kodia Jungle sunset point", "Apple orchard walks", "Surkanda Devi Temple trek", "Camping in pine forests", "Offbeat and uncrowded", "Stargazing sessions"],
    price: 1999,
    mapImage: "https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800&h=500&fit=crop",
  },
  {
    id: "chakrata",
    title: "Chakrata Backpacking",
    subtitle: "The Offbeat Army Town",
    location: "Chakrata, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "2N/3D",
    bestSeason: "March - June, September - November",
    rating: "4.3",
    reviewCount: "3k+",
    images: ["https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=1200&h=600&fit=crop"],
    brief: "A hidden gem with pristine forests, waterfalls, and the Tiger Falls — one of India's highest direct waterfalls.",
    description: "Chakrata is an offbeat cantonment town with unparalleled natural beauty. Visit Tiger Falls, hike through dense deodar forests, explore ancient caves, and enjoy absolute solitude away from tourist crowds.",
    highlights: ["Tiger Falls — one of India's highest waterfalls", "Deodar forest hikes", "Budher Caves exploration", "Chakrata Canal walk", "Sunrise at Chilmiri Neck", "Offbeat solitude"],
    price: 1999,
    mapImage: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=500&fit=crop",
  },
  {
    id: "dhanaulti",
    title: "Dhanaulti Backpacking",
    subtitle: "The Frosty Hill Retreat",
    location: "Dhanaulti, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "2N/3D",
    bestSeason: "March - June, December - February",
    rating: "4.5",
    reviewCount: "5k+",
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=600&fit=crop"],
    brief: "A peaceful eco-tourism destination with thick deodar forests and snow-covered winters.",
    description: "Dhanaulti offers a refreshing break from crowded hill stations. Walk through Eco Park's deodar forests, enjoy snow in winter, and take in panoramic views of the Himalayan range from the Dhanaulti ridge.",
    highlights: ["Eco Park deodar walks", "Snow camping in winter", "Himalayan ridge views", "Thunder World adventure park", "Camping and bonfire nights", "Peaceful uncrowded trails"],
    price: 1999,
    mapImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop",
  },
  {
    id: "auli",
    title: "Auli Backpacking",
    subtitle: "India's Skiing Paradise",
    location: "Auli, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "3N/4D",
    bestSeason: "November - March",
    rating: "4.7",
    reviewCount: "7k+",
    images: ["https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=1200&h=600&fit=crop"],
    brief: "India's premier skiing destination with breathtaking views of Nanda Devi and the Garhwal peaks.",
    description: "Auli is a paradise for adventure backpackers. Famous for its world-class skiing slopes, the Auli ropeway (India's longest cable car), and spectacular close-up views of Nanda Devi, Trishul, and Dronagiri peaks.",
    highlights: ["Skiing on Asia's best slopes", "Auli ropeway — India's longest cable car", "Nanda Devi panoramic views", "Gorson Bugyal meadow trek", "Joshimath visit", "Snow camping"],
    price: 4999,
    mapImage: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800&h=500&fit=crop",
  },
  {
    id: "munsiyari",
    title: "Munsiyari Backpacking",
    subtitle: "The Little Kashmir",
    location: "Munsiyari, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "3N/4D",
    bestSeason: "March - June, September - November",
    rating: "4.6",
    reviewCount: "4k+",
    images: ["https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop"],
    brief: "A remote Himalayan outpost with panoramic views of the Panchachuli peaks, ideal for offbeat backpackers.",
    description: "Munsiyari, the base for numerous Himalayan treks, offers stunning views of the Panchachuli peaks. Explore tribal villages, visit the Birthi and Kalamuni waterfalls, and trek through pristine oak and rhododendron forests.",
    highlights: ["Panchachuli peak panoramic views", "Birthi and Kalamuni waterfalls", "Tribal village walks", "Dark sky stargazing", "Treks to Khaliya Top and Maheshwari Kund", "Offbeat Himalayan outpost"],
    price: 3999,
    mapImage: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=500&fit=crop",
  },
  {
    id: "kartik-swami",
    title: "Kartik Swami Backpacking",
    subtitle: "The Temple Village Escape",
    location: "Kartik Swami, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "2N/3D",
    bestSeason: "March - June, September - November",
    rating: "4.3",
    reviewCount: "2k+",
    images: ["https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=600&fit=crop"],
    brief: "A spiritual hilltop village with a famous temple and sweeping Himalayan views, far from the crowds.",
    description: "Kartik Swami is a hidden gem perched atop a hill with a 360-degree view of the Garhwal Himalayas. The Kartik Swami Temple dedicated to Lord Kartikeya offers breathtaking sunrise views and a peaceful atmosphere.",
    highlights: ["Kartik Swami Temple with 360° Himalayan views", "Sunrise from the temple hilltop", "Offbeat and crowd-free", "Forest walks and birdwatching", "Nearby Kanatal and Tehri Dam", "Budget-friendly destination"],
    price: 1499,
    mapImage: "https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800&h=500&fit=crop",
  },
  {
    id: "lansdowne",
    title: "Lansdowne Backpacking",
    subtitle: "The Quiet Cantonment Town",
    location: "Lansdowne, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "2N/3D",
    bestSeason: "March - June, September - November",
    rating: "4.4",
    reviewCount: "3k+",
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=1200&h=600&fit=crop"],
    brief: "A sleepy cantonment hill station surrounded by oak forests, perfect for a quiet backpacking weekend.",
    description: "Lansdowne is a charming, unhurried hill station with colonial-era architecture, dense oak and pine forests, and beautiful viewpoints like Tiffin Top and Bhulla Tal. The Garhwal Rifles Regimental Museum adds a historical touch.",
    highlights: ["Tiffin Top and Bhulla Tal viewpoints", "Garhwal Rifles Regimental Museum", "Oak and pine forest walks", "Colonial cantonment charm", "St. Mary's Church heritage", "Peaceful weekend escape"],
    price: 1499,
    mapImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop",
  },
  {
    id: "jim-corbett",
    title: "Jim Corbett Backpacking",
    subtitle: "India's Oldest National Park",
    location: "Jim Corbett National Park, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "2N/3D",
    bestSeason: "November - June",
    rating: "4.6",
    reviewCount: "12k+",
    images: ["https://images.unsplash.com/photo-1549366021-9f761d450616?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=600&fit=crop"],
    brief: "India's first national park and a premier wildlife destination for spotting Bengal tigers, elephants, and exotic birds.",
    description: "Jim Corbett National Park is a must-visit for wildlife backpackers. Jeep safaris through the Dhikala, Bijrani, and Jhirna zones offer chances to spot Bengal tigers, Asian elephants, crocodiles, and over 600 bird species.",
    highlights: ["Bengal tiger safari", "Elephant safari at Dhikala", "Corbett Museum and heritage", "River rafting on Kosi River", "Bird watching (600+ species)", "Camping on the park periphery"],
    price: 3999,
    mapImage: "https://images.unsplash.com/photo-1549366021-9f761d450616?w=800&h=500&fit=crop",
  },
  {
    id: "jageshwar-nainital",
    title: "Jageshwar & Nainital Backpacking",
    subtitle: "Temples & Lakes",
    location: "Nainital, Uttarakhand",
    state: "Uttarakhand",
    region: "uttarakhand",
    duration: "2N/3D",
    bestSeason: "March - June, September - November",
    rating: "4.5",
    reviewCount: "8k+",
    images: ["https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=1200&h=600&fit=crop"],
    brief: "Combine the lake charm of Nainital with the ancient temple cluster of Jageshwar for a diverse backpacking trip.",
    description: "This circuit covers Nainital's Naini Lake, Mall Road, and Snow View Point alongside Jageshwar's 124 ancient temples dedicated to Lord Shiva, set in a serene deodar forest. A perfect blend of nature, heritage, and spirituality.",
    highlights: ["Naini Lake boating", "Mall Road and Tibetan Market", "Snow View Point ropeway", "Jageshwar's 124 ancient temples", "Deodar forest walks at Jageshwar", "Heritage and spirituality blend"],
    price: 2999,
    mapImage: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=500&fit=crop",
  },
  {
    id: "manali",
    title: "Manali Backpacking",
    subtitle: "The Valley of Gods",
    location: "Manali, Himachal Pradesh",
    state: "Himachal Pradesh",
    region: "himachal",
    duration: "3N/4D",
    bestSeason: "October - June",
    rating: "4.8",
    reviewCount: "20k+",
    images: ["https://images.unsplash.com/photo-1586350977770-2598f1b6b7c8?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop"],
    brief: "The ultimate backpacking hub in Himachal with Solang Valley, Old Manali cafes, and easy access to high-altitude passes.",
    description: "Manali is the crown jewel of Himachal backpacking. From the vibrant cafes of Old Manali to the adventure activities of Solang Valley, ancient Hadimba Temple to the hot springs of Vashisht, Manali offers endless exploration.",
    highlights: ["Old Manali cafe culture", "Solang Valley paragliding and skiing", "Hadimba Temple and Vashisht hot springs", "Rohtang Pass day trip", "Naggar Castle heritage", "River-side camping"],
    price: 3499,
    mapImage: "https://images.unsplash.com/photo-1586350977770-2598f1b6b7c8?w=800&h=500&fit=crop",
  },
  {
    id: "kasol",
    title: "Kasol Backpacking",
    subtitle: "The Mini Israel of India",
    location: "Kasol, Himachal Pradesh",
    state: "Himachal Pradesh",
    region: "himachal",
    duration: "3N/4D",
    bestSeason: "March - June, September - November",
    rating: "4.6",
    reviewCount: "15k+",
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&h=600&fit=crop"],
    brief: "The backpacker capital of Himachal nestled in the Parvati Valley with Israel-style cafes and riverside camping.",
    description: "Kasol is legendary among backpackers for its laid-back vibe, Israeli cafes, riverside campsites, and access to the Parvati Valley. Explore nearby villages, visit Manikaran Sahib, and trek to Kheerganga's hot springs.",
    highlights: ["Israeli cafe culture and bakeries", "Parvati River camping", "Manikaran Sahib hot springs", "Kheerganga trek", "Chalal and Rasol village walks", "Magnet for global backpackers"],
    price: 2999,
    mapImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop",
  },
  {
    id: "jibhi",
    title: "Jibhi Backpacking",
    subtitle: "The Hidden Paradise of Tirthan",
    location: "Jibhi, Himachal Pradesh",
    state: "Himachal Pradesh",
    region: "himachal",
    duration: "3N/4D",
    bestSeason: "March - June, September - November",
    rating: "4.6",
    reviewCount: "5k+",
    images: ["https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop"],
    brief: "A serene riverside backpacking paradise in the Tirthan Valley with hidden waterfalls and treehouse stays.",
    description: "Jibhi is a tranquil haven in the Tirthan Valley, known for its crystal-clear rivers, ancient wooden bridges, treehouse accommodations, and the beautiful Jibhi Waterfall. Ideal for slow travelers and nature lovers.",
    highlights: ["Jibhi Waterfall and river pools", "Treehouse and riverside stays", "Ancient wooden architecture", "Tirthan Valley trout fishing", "Serolsar Lake trek", "Slow travel paradise"],
    price: 2499,
    mapImage: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=500&fit=crop",
  },
  {
    id: "tirthan-valley",
    title: "Tirthan Valley Backpacking",
    subtitle: "The Trout Fishing Haven",
    location: "Tirthan Valley, Himachal Pradesh",
    state: "Himachal Pradesh",
    region: "himachal",
    duration: "3N/4D",
    bestSeason: "March - June, September - November",
    rating: "4.5",
    reviewCount: "4k+",
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&h=600&fit=crop"],
    brief: "A pristine valley on the outskirts of the Great Himalayan National Park, famous for trout fishing and forest treks.",
    description: "Tirthan Valley is a slice of paradise along the Tirthan River, forming the gateway to the Great Himalayan National Park (UNESCO). Enjoy trout fishing, riverside camping, waterfall treks, and authentic Himachali village life.",
    highlights: ["Great Himalayan National Park entry", "Trout fishing in the Tirthan River", "Riverside camping and bonfires", "Waterfall and forest treks", "Himachali village homestays", "Offbeat weekend escape"],
    price: 2999,
    mapImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop",
  },
  {
    id: "dharamshala-mcleodganj",
    title: "Dharamshala & McLeodganj Backpacking",
    subtitle: "The Little Lhasa of India",
    location: "Dharamshala, Himachal Pradesh",
    state: "Himachal Pradesh",
    region: "himachal",
    duration: "3N/4D",
    bestSeason: "March - June, September - November",
    rating: "4.7",
    reviewCount: "18k+",
    images: ["https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1586350977770-2598f1b6b7c8?w=1200&h=600&fit=crop"],
    brief: "The residence of His Holiness the Dalai Lama, blending Tibetan Buddhist culture with Himalayan adventure.",
    description: "McLeodganj, the home of the Dalai Lama, is a unique backpacking destination. Explore the Tsuglagkhang Temple, Bhagsu Waterfall, Triund trek, and the vibrant Tibetan community with its monasteries, cafes, and craft markets.",
    highlights: ["Dalai Lama Temple and Tibetan culture", "Bhagsu Waterfall and Naddi views", "Triund Trek from McLeodganj", "Tibetan Museum and crafts", "Kangra tea gardens", "Buddhist monastery meditation"],
    price: 2999,
    mapImage: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=500&fit=crop",
  },
  {
    id: "bir-billing",
    title: "Bir Billing Backpacking",
    subtitle: "The Paragliding Capital of India",
    location: "Bir Billing, Himachal Pradesh",
    state: "Himachal Pradesh",
    region: "himachal",
    duration: "2N/3D",
    bestSeason: "March - June, September - November",
    rating: "4.7",
    reviewCount: "8k+",
    images: ["https://images.unsplash.com/photo-1551632811-561732d1e306?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop"],
    brief: "The world's second-best paragliding destination with a vibrant backpacker vibe and Tibetan monasteries.",
    description: "Bir Billing is famous worldwide for paragliding. Beyond flying, enjoy mountain biking, trekking through tea gardens, visiting the serene Bir Monastery, and exploring the lively backpacker cafes and hostels.",
    highlights: ["Paragliding from Billing — world's 2nd best site", "Bir Monastery and Tibetan colony", "Mountain biking trails", "Tea garden walks", "Backpacker cafe culture", "Camping under the stars"],
    price: 2499,
    mapImage: "https://images.unsplash.com/photo-1551632811-561732d1e306?w=800&h=500&fit=crop",
  },
  {
    id: "dalhousie",
    title: "Dalhousie Backpacking",
    subtitle: "The Swiss of Himachal",
    location: "Dalhousie, Himachal Pradesh",
    state: "Himachal Pradesh",
    region: "himachal",
    duration: "2N/3D",
    bestSeason: "March - June, September - February",
    rating: "4.5",
    reviewCount: "7k+",
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=600&fit=crop"],
    brief: "A colonial-era hill station with European charm, pine-clad hills, and panoramic valley views.",
    description: "Dalhousie offers a nostalgic backpacking experience with its colonial architecture, five picturesque hills (Kathlog, Patreyn, Tehra, Bakrota, Bhangora), and stunning views of the Pir Panjal range. Visit Khajjiar, the Mini Switzerland of India.",
    highlights: ["Khajjiar — Mini Switzerland of India", "Panch Pulla and Satdhara Falls", "Colonial-era St. John's Church", "Subhash Baoli viewpoint", "Pine forest walks on five hills", "Dalhousie heritage trail"],
    price: 2499,
    mapImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop",
  },
  {
    id: "shimla",
    title: "Shimla Backpacking",
    subtitle: "The Queen of Hill Stations",
    location: "Shimla, Himachal Pradesh",
    state: "Himachal Pradesh",
    region: "himachal",
    duration: "2N/3D",
    bestSeason: "March - June, September - December",
    rating: "4.6",
    reviewCount: "20k+",
    images: ["https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop"],
    brief: "India's most iconic hill station with the famous Mall Road, Ridge, and toy train — a colonial masterpiece.",
    description: "Shimla, the summer capital of British India, is a classic backpacking destination. Walk the Mall Road and Ridge, ride the UNESCO-listed Kalka-Shimla Toy Train, explore Jakhoo Temple, and visit the Viceregal Lodge.",
    highlights: ["Mall Road and Scandal Point", "Ridge with Himalayan views", "Kalka-Shimla Toy Train (UNESCO)", "Jakhoo Temple and Hanuman statue", "Viceregal Lodge heritage", "Ice skating and snow in winter"],
    price: 2499,
    mapImage: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=800&h=500&fit=crop",
  },
  {
    id: "spiti-summer",
    title: "Spiti Valley Backpacking (Summer)",
    subtitle: "The Cold Desert Mountain Adventure",
    location: "Spiti Valley, Himachal Pradesh",
    state: "Himachal Pradesh",
    region: "himachal",
    duration: "7N/8D",
    bestSeason: "June - October",
    rating: "4.8",
    reviewCount: "10k+",
    images: ["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=1200&h=600&fit=crop"],
    brief: "A breathtaking summer journey through the ancient Buddhist kingdom of Spiti — a high-altitude cold desert.",
    description: "Spiti Valley in summer (June-October) is accessible via Shimla and offers a surreal landscape of Buddhist monasteries (Key, Tabo, Dhankar), high-altitude villages (Kibber, Hikkim, Komic), and pristine lakes (Chandratal).",
    highlights: ["Key Monastery and Tabo Monastery", "Chandratal Lake — Moon Lake", "Hikkim — highest post office in the world", "Komic — highest motorable village", "Pin Valley National Park", "Cross Kunzum Pass and Rohtang Pass"],
    price: 9999,
    mapImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop",
  },
  {
    id: "spiti-winter",
    title: "Spiti Valley Backpacking (Winter)",
    subtitle: "The Frozen Desert Expedition",
    location: "Spiti Valley, Himachal Pradesh",
    state: "Himachal Pradesh",
    region: "himachal",
    duration: "7N/8D",
    bestSeason: "November - March",
    rating: "4.7",
    reviewCount: "3k+",
    images: ["https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=1200&h=600&fit=crop", "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=600&fit=crop"],
    brief: "An extreme winter expedition into a frozen Spiti — snow-blanketed monasteries, frozen rivers, and complete solitude.",
    description: "Winter Spiti is a completely different world. With temperatures dropping to -30°C, the valley transforms into a frozen wonderland. Accessible only via the Shimla route, this is for the truly adventurous seeking absolute solitude.",
    highlights: ["Frozen Chandratal Lake trek", "Snow-covered Key Monastery", "Winter homestays with Bukhari heating", "Frozen waterfalls and rivers", "Stargazing in the clearest skies", "Extreme cold weather experience (-30°C)"],
    price: 12999,
    mapImage: "https://images.unsplash.com/photo-1486911278844-a81c5267e227?w=800&h=500&fit=crop",
  },
];
