import type { ItineraryDay } from '@/lib/content/treks/types';

/** Day-wise itinerary for Brahmatal — shown in the trek detail accordion. */
export const BRAHMATAL_ITINERARY: ItineraryDay[] = [
  {
    day: 1,
    title: 'Drive from Rishikesh to Lohajung',
    description: [
      'Distance: ~250 km · Time: 10–12 hrs · Pickup: ISBT Rishikesh, 6:15 AM · Overnight: Lohajung guesthouse · Altitude on arrival: ~7,600 ft.',
      'Rishikesh is the starting point of the adventure. You will be picked up by our transport manager at the ISBT in Rishikesh at 6:15 in the morning, and from there you will be driven to Lohajung — the mountain settlement that serves as the base for the Brahmatal climb.',
      'About 250 kilometres separate Lohajung (Chamoli district, Uttarakhand) from Rishikesh. The journey typically takes 10–12 hours, depending on traffic and road conditions. Indian Treks arranges Bolero, Tata Sumo, or Tempo Traveller vehicles for the transfer to Lohajung. On arrival you are assigned a room in the guesthouse.',
      'You travel through mountain roads as you leave Rishikesh. If the weather is clear, you may glimpse the Garhwal Himalayas in the distance. The River Ganga keeps you company while you take in the serene scenery.',
      'Along the highway you pass three of the most important holy confluences in the region — Devprayag, Rudraprayag, and Karnaprayag.',
      'At Devprayag, the Alaknanda meets the Bhagirathi for the first time. On a clear day you can make out the different shades of teal and turquoise where the two rivers join.',
      'Continuing through Srinagar (Garhwal), you reach Rudraprayag — the confluence of the Mandakini and the Alaknanda. About 33 km further along the road you arrive at Karnaprayag, where the Pindar joins the Alaknanda.',
      'From Karnaprayag the road turns toward Tharali and Deval before the final climb into Lohajung. As you ascend, the majestic Nanda Ghunti massif often comes into striking proximity. If you reach Lohajung before dusk, you may catch a sunset painting the ridges in warm hues.',
      'Local legend gives the settlement its name: villagers say the goddess Parvati fought the demon Lohasur in a “jung” (war) here — hence “Lohajung.”',
      'Lohajung has a small market where you can pick up camping essentials and last-minute trek supplies. Sitting high on a ridge, evenings can be brisk; depending on the season it may also be cloudy or wet. Pack layers so you can adjust to changing temperatures through the day.',
      'Overnight stay in a guesthouse at Lohajung. Trek briefing with the Indian Treks team.',
    ].join('\n\n'),
    meals: 'Dinner',
    altitude: '7,600 ft (Lohajung)',
    distance: '~250 km drive',
    duration: '10–12 hrs',
  },
  {
    day: 2,
    title: 'Trek from Lohajung to Bekaltal',
    description: [
      'Distance: 6 km trek · Time: ~5 hrs · Altitude: ~7,600 ft → ~9,800 ft · Overnight: Twin-sharing tents at Bekaltal campsite.',
      'Today is the first walking day. After breakfast at Lohajung, the group sets out toward Bekaltal — a gentle, well-marked ascent of about six kilometres through oak, fir, cedar and rhododendron forest.',
      'On clear stretches you are treated to stunning views of Mount Nanda Ghunti. After a short walk you reach Mandoli (Mundoli), the first mountain village on the route, which appears on your left as the trail continues.',
      'The path gradually ascends across the ridges, winding and bending as it gains height. From open sections you can look toward the Kali Valley, where the Kali and Pindar rivers meet far below.',
      'Beyond Mandoli the trail enters denser woodland. In spring and late winter, rhododendron blossoms bring colour to the mountainsides; in peak winter the same path can be completely covered in snow. The scent of cut wood and forest undergrowth is one of the day’s most memorable details.',
      'After roughly two hours you reach a wooden bridge about ten metres long spanning a creek (Link-gaad). Water may need to be rationed at this source depending on the season. Crossing the bridge brings you to Begum — a serene clearing and an ideal rest stop, with views of Navali and Bagdi Bugyal and Nanda Ghunti still dominating the skyline.',
      'Continue for about twenty minutes past two neighbouring streams to Gujreni. Some groups camp here, but Indian Treks continues to Bekaltal. Gujreni is excellent for birdwatching — look for species such as the Asian Barred Owlet, woodpeckers, Solitary Snipe and Blue-fronted Redstarts.',
      'The final stretch is the last push of the day. About an hour and a half of forest walking brings you near Bekaltal Lake; the campsite sits roughly fifteen minutes from the water. After pitching twin-sharing tents, rest, then visit the lake later in the day.',
      'Bekaltal sits in a thick oak grove. Its waters keep a distinctive dark-brown tint from organic matter leaching into the lake. In cold weather a thin film of ice may form on the surface. After a sunset at the lake, return to camp for a hot dinner and overnight in tents.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '9,800 ft (Bekaltal)',
    distance: '6 km trek',
    duration: '~5 hrs',
  },
  {
    day: 3,
    title: 'Trek from Bekaltal to Brahmatal Lake',
    description: [
      'Distance: 7 km trek · Time: ~5–7 hrs · Altitude: ~9,800 ft → ~10,450–11,250 ft · Overnight: Twin-sharing tents at Brahmatal / Khabekhal.',
      'Utilize the snowy pathways to your advantage as you make your way from Bekaltal toward Brahmatal. Depending on snow and trail conditions, the walk typically takes about four to seven hours.',
      'The path winds through oak and rhododendron forest before opening onto the ridge meadows of Telindi (Tilandi) Top. From here you are rewarded with beautiful Himalayan views when the weather is clear — a highlight of the day.',
      'Stay on the trail beyond Telindi; a gradual approach brings you to Brahmatal Lake, also known locally as Khabekhal. Twin-sharing tents are pitched near the lake for the night. Rest, enjoy a hot meal, and take in the quiet alpine setting around camp.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '11,250 ft (Brahmatal)',
    distance: '7 km trek',
    duration: '~5–7 hrs',
  },
  {
    day: 4,
    title: 'Brahmatal Lake to Summit and descend to Daldum',
    description: [
      'Distance: ~12 km trek · Time: ~8–9 hrs · Altitude: Brahmatal camp → ~12,150 ft (summit) → Daldum camp (~9,350–10,000 ft) · Overnight: Twin-sharing tents at Daldum.',
      'After breakfast, prepare for the ascent to Brahmatal Top — the most visually striking day of the trek. The route climbs over Chota Jhandidar and Bada Jhandidar on an exposed ridge trail with valleys dropping away on either side. Sections can feel committing in snow or wind; follow your trek leader closely.',
      'It typically takes about two and a half to three hours to reach Brahmatal Top. Pause here for magnificent views of the snow-capped Himalayan ranges. Mount Trishul stands close by, with Nanda Ghunti (Nandhaghunti) also commanding the skyline when visibility is clear.',
      'From the summit, continue toward the next campsite at Daldum. The descent through forest usually takes up to about three hours and covers roughly 2.7 km on this final leg — slower when the trail is snowy or slippery. Oak and rhododendron woodland accompany you most of the way down.',
      'Arrive Daldum by afternoon or early evening, pitch twin-sharing tents, enjoy a hot dinner, and rest overnight.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '12,150 ft (summit) → Daldum',
    distance: '12 km trek',
    duration: '~8–9 hrs',
  },
  {
    day: 5,
    title: 'Trek from Daldum Camp to Lohajung',
    description: [
      'Distance: 4 km trek · Time: ~3–5 hrs · Altitude: Daldum → ~7,600 ft (Lohajung) · Overnight: Lohajung guesthouse.',
      'From Daldum, take the left fork toward Lohajung. It is a short hike of about four kilometres and usually takes three to five hours depending on snow and pace.',
      'The well-marked path crosses a few streams and continues through the same oak and rhododendron forest you walked earlier in the trek. As you move through the trees you will pass shepherd’s huts used by locals to shelter livestock.',
      'From there, follow the stone-paved path that links the mountain settlements with Lohajung. Arrive at the village, freshen up at the guesthouse, and spend the later evening exploring the small town.',
      'Sunsets from Lohajung are often breathtaking — a last look at the ridges before you leave. If you want mementos from the expedition, pick them up in the local market. The guesthouse serves a hearty meal; rest well overnight. Tomorrow you drive back to Rishikesh.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '7,600 ft (Lohajung)',
    distance: '4 km trek',
    duration: '~3–5 hrs',
  },
  {
    day: 6,
    title: 'Drive from Lohajung to Rishikesh',
    description: [
      'Distance: ~210–250 km drive · Time: 10–12 hrs · Drop: Rishikesh (ETA around 7:00 PM, traffic-dependent) · Meals: Breakfast.',
      'As this incredible trip draws to a close, we bring you back to Rishikesh today. After your last morning tea and breakfast with the crew, the group departs Lohajung toward Rishikesh.',
      'The road distance is typically about 210–250 km and takes around 10–12 hours, following the same corridor you travelled on Day 1 — Deval, Tharali, Karnaprayag, Rudraprayag, Srinagar (Garhwal) and Devprayag.',
      'Arrival in Rishikesh is usually expected around 7:00 in the evening, though exact timing can change with route conditions and traffic. The Brahmatal trek concludes on drop at Rishikesh.',
    ].join('\n\n'),
    meals: 'Breakfast',
    altitude: '~2,100 ft (Rishikesh)',
    distance: '~210–250 km drive',
    duration: '10–12 hrs',
  },
];
