import type { ItineraryDay } from '@/lib/content/treks/types';

/** Day-wise itinerary for Chopta Tungnath — shown in the trek detail accordion. */
export const CHOPTA_TUNGNATH_ITINERARY: ItineraryDay[] = [
  {
    day: 1,
    title: 'Rishikesh railway station pickup — Drive to Chopta camp',
    description: [
      'Total distance: 202 km · Duration: 7–8 hours · Pickup: Rishikesh railway station at 7:30 AM · Mode: Tempo Traveller · Elevation: Chopta camp, 2,680 m (8,800 ft) · Overnight: camp stay.',
      'Indian Treks organizes pickup for trekkers from Rishikesh railway station in the morning. Vehicles assemble around 7:30 AM — report on time so the group can depart together. The scenic drive to Chopta takes you through some of Uttarakhand\'s most revered river valleys and hill towns before you reach the meadows that serve as your base for Tungnath and Chandrashila.',
      'You can travel through Uttarakhand\'s remarkable landscape on the picturesque route from Rishikesh to Chopta. Here are a few highlights along the journey:',
      'Rishikesh: On the banks of the Ganges sits this holy city, renowned for its yoga centres, ashrams, and adventure sports like bungee jumping and white-water rafting. Known as the Yoga Capital of the World, Rishikesh is also home to several ancient temples and the iconic Laxman Jhula and Ram Jhula.',
      'Devprayag: A small town where the Alaknanda and Bhagirathi rivers meet to form the Ganges. One of Uttarakhand\'s holiest locations, Devprayag is dotted with ancient temples and offers a powerful first glimpse of Himalayan river confluence culture.',
      'Rudraprayag: Situated where the Mandakini and Alaknanda rivers converge, Rudraprayag is regarded as one of the Panch Prayag (five sacred confluences) of the Ganges. The town is surrounded by forested hills and serves as an important stop on the route toward the upper Garhwal Himalayas.',
      'Sari Village: At the foot of the Deoriatal trail lies the quiet hamlet of Sari. It offers sweeping views of Himalayan peaks and is a popular starting point for the Deoriatal trek — a relatively easy 2–3 hour walk from the village to the lake. Many Chopta itineraries pass through this region, giving you a feel for the lower Himalayan countryside before the meadows open up.',
      'As the road climbs higher, pine and rhododendron forests line the route and the air turns crisp. Chopta — often called the Mini Switzerland of India — welcomes you with rolling alpine meadows and wide-open views of snow-capped peaks.',
      'Arrival at Chopta camp: Check in, freshen up, and settle into your tents. Enjoy evening tea with mountain views, followed by a trek briefing and dinner. Overnight stay at the Chopta camp under clear Himalayan skies.',
    ].join('\n\n'),
    meals: 'Dinner',
    altitude: '8,800 ft (Chopta)',
    distance: '202 km drive',
    duration: '7–8 hrs',
  },
  {
    day: 2,
    title: 'Chopta to Tungnath & Chandrashila summit — return to Sari village',
    description: [
      'Trek distance: 5 km one way (3.5 km Chopta–Tungnath + 1.5 km Tungnath–Chandrashila) · Duration: 4–5 hours ascent · Mode: on foot · Highest point: Chandrashila, 4,130 m (13,550 ft) · Overnight: Sari village.',
      'The renowned and beginner-friendly climb from Chopta to Tungnath and Chandrashila Peak lies in Uttarakhand\'s Garhwal Himalayas. After an early breakfast at camp, the group sets out from Chopta on the well-marked forest trail toward the summit.',
      'Distance: The walk from Chopta to Tungnath Temple covers approximately 3.5 km and takes two to three hours at a comfortable pace. From Tungnath, the climb to Chandrashila Peak is about 1.5 km and typically takes around one hour.',
      'Incredible views: The trail opens to breathtaking vistas of Himalayan giants — Chaukhamba, Nanda Devi, Trishul, Kedar Peak, and Bandarpunch. Chandrashila\'s summit is especially rewarding for photography, with wide-angle panoramas in every direction.',
      'Tungnath Temple: The highest Shiva temple on earth sits at 3,680 m (12,073 ft), surrounded by snow-draped peaks. A revered stop on the Panch Kedar circuit, it blends spiritual significance with raw Himalayan beauty — most trekkers pause here before the final push to the summit.',
      'Chandrashila Peak: Rising to 4,130 m (13,550 ft), Chandrashila offers sweeping 360° views across the Garhwal ranges. A modest shrine devoted to Lord Shiva marks the top — a fitting reward after the short but steep final section.',
      'Trekking infrastructure: The Chopta–Tungnath–Chandrashila route is a well-established trail with campsites, potable water points, and basic facilities along the way, making the day comfortable and accessible for a wide range of ages and fitness levels.',
      'After summit celebrations and packed lunch at the top or midway, descend the same route back toward the valley. Continue to Sari village for check-in, evening tea, dinner, and overnight stay — perfectly placed for the Deoriatal excursion on Day 3.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '13,550 ft (Chandrashila)',
    distance: '10 km round trip',
    duration: '6–7 hrs',
  },
  {
    day: 3,
    title: 'Sari village to Deoria Tal — return to road head & drive to Rishikesh',
    description: [
      'Morning trek from Sari · Return same day · Drive: 220 km to Rishikesh · Duration: 7–8 hours · Expected arrival: 8:30–9:30 PM · Trip ends in Rishikesh.',
      'After breakfast at Sari village, begin the Deoria Tal trek. The trail from Sari is clean, well-maintained, and paved with stone steps in sections — you pass local homes and a small temple as the village fades behind you.',
      'The path gradually steepens, but as the forest thins, Chandrashila Peak and Tungnath temple come into view from higher up — a rewarding glimpse of the summit you conquered the previous day.',
      'Hawa Ghar: Midway up the climb, you reach a rest shelter built by the forest department. Pause here to catch your breath and take in the widening valley views before continuing toward the lake.',
      'Rhododendron and maple trees line the upper trail, offering shade as you walk. Valley vistas open on either side until the path descends gently toward Deoria Tal — where wildflowers, bird calls, and the stillness of the lake calm the mind.',
      'Spend time at Deoria Tal absorbing the reflection of Chaukhamba on clear days, then retrace the trail back to Sari and the road head. Collect your bags and board the vehicle for the return journey to Rishikesh.',
      'The drive from Chopta/Sari to Rishikesh normally takes 7–8 hours covering 220 km. The route passes through beautiful hill country with several natural stops along the way. Highlights on the journey back include:',
      'Ukhimath: A small settlement on the route from Chopta to Rishikesh and an important regional pilgrimage centre known for its ancient temples. On clear days, the town offers fine views of surrounding Himalayan peaks.',
      'Rudraprayag: Where the Mandakini and Alaknanda rivers meet — a sacred confluence town renowned for its temples and dramatic river scenery.',
      'Devprayag: Where the Bhagirathi and Alaknanda merge to form the Ganges. One of the holiest towns in Garhwal and traditionally regarded as the birthplace of the sacred river.',
      'Ganges river views: For long stretches the road follows the Ganges valley, with frequent viewpoints to pause and appreciate the river that shapes the spiritual and cultural life of the region.',
      'You will arrive in Rishikesh between 8:30 and 9:30 PM. Trip ends on arrival — plan your onward train or bus connections accordingly.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch',
    altitude: '8,000 ft (Deoria Tal)',
    distance: '6 km trek + 220 km drive',
    duration: 'Full day',
  },
];
