import type { ItineraryDay } from '@/lib/content/treks/types';

/** Day-wise itinerary for Kedarkantha — shown in the trek detail accordion. */
export const KEDARKANTHA_ITINERARY: ItineraryDay[] = [
  {
    day: 1,
    title: 'Dehradun Railway Station pickup — Drive to Sankri (base camp)',
    description: [
      'Total distance: 190 km · Duration: 8–9 hours · Mode: Tempo Traveller · Elevation: Sankri Base Camp, 1,920 m (6,400 ft) · Overnight: our partner hotels in Sankri.',
      'Indian Treks organizes transport for trekkers from Dehradun Railway Station in the morning. Vehicles leave for Sankri around 6:00–7:00 AM — report on time so the group can depart together. The drive follows the standard hill road via Mussoorie, Nainbagh, Naugaon, Purola, Mori, and Netwar.',
      'Uttarakhand\'s capital, Dehradun, is one of India\'s most beautiful cities. Rajpur Road is the area\'s main attraction; as you drive along it, you get an early sense of Dehradun\'s charm before heading toward Vikasnagar and the mountain road beyond.',
      'The road to Sankri, the base camp for many famous Himalayan treks, is a journey in itself. Starting from Dehradun, the drive takes you through winding mountain roads, lush valleys, charming villages, and dense forests — a taste of Himalayan beauty before the trek even begins.',
      'Dehradun to Mussoorie and Nainbagh: The road climbs from Dehradun through Mussoorie and Nainbagh toward the Yamunotri–Gangotri hill highway.',
      'Naugaon to Purola: From Naugaon the route continues along the Tons valley toward Purola — the main motorable corridor used by Kedarkantha groups.',
      'Purola to Mori and Netwar: After Purola, the road follows the Tons River through Mori and Netwar, the gateway to Govind Pashu Vihar.',
      'Charming villages and forests: The route is dotted with small hamlets and farmlands. Terraced fields, apple orchards, and wooden houses showcase the simple yet beautiful lifestyle of mountain communities. Pine and deodar forests line the roads, adding freshness to the journey.',
      'The valleys and Tons River: Approaching Sankri, you enter the breathtaking Tons River Valley. The turquoise river flows gracefully between lush green mountains, offering postcard-perfect views that make the drive unforgettable.',
      'The final stretch: The last leg takes you through dense forests and narrow mountain roads. Though the drive can be adventurous, unfolding vistas of snow-capped peaks make every turn worth it.',
      'Arrival at Sankri: Finally, you reach Sankri (6,400 ft), a serene village nestled in the Western Garhwal Himalayas. Stunning views of Swargarohini peaks, vibrant sunsets, and starry skies welcome you warmly before the trek begins.',
      'Check in at the hotel, freshen up, and enjoy evening snacks with mountain views. After a short trek briefing and an optional village walk, return for dinner and an overnight stay in Sankri.',
    ].join('\n\n'),
    meals: 'Dinner',
    altitude: '6,400 ft (Sankri)',
    distance: '190 km drive',
    duration: '8–9 hrs',
  },
  {
    day: 2,
    title: 'From Sankri to Juda Ka Talab trek',
    description: [
      'Trek distance: 5 km · Duration: 4–5 hours · Travel method: on foot · Elevation: Juda Ka Talab, 2,700 m (9,000 ft) · Accommodation: shared camp in tents.',
      'Today, a warm morning awaits you. Feel the peace in the mountains — no connectivity or distractions, just the quiet of the Himalayas.',
      'Enjoy a cup of coffee or tea at 6:00 AM and breakfast at 7:30 AM. The group departs at 8:30 AM, following your trek leader\'s instructions.',
      'The trek from Sankri to Juda Ka Talab on the way to Kedarkantha is an enjoyable walk through the lush forests of Uttarakhand\'s Govind National Park. Here are the highlights along the trail:',
      'Sankri (base camp): Your trek begins from the quaint village of Sankri (6,400 ft). Surrounded by snow-clad peaks, apple orchards, and lush meadows, Sankri is a picture-perfect Himalayan hamlet that sets the tone for the journey ahead.',
      'Forest trail: As you leave Sankri, the trail leads into dense forests of pine, oak, and rhododendron. The walk is refreshing, with the fragrance of pine in the air and birdsong all around. In spring, blooming rhododendrons add splashes of red and pink, bringing the forest to life.',
      'Scenic views along the way: Every now and then, the trees open up to reveal glimpses of mighty Himalayan peaks. On clear days, you can spot the Swargarohini range, Bandarpoonch, and Black Peak in the distance — each view more rewarding than the last.',
      'Water crossings: The route is sprinkled with small streams and natural water crossings. These make for refreshing halts — refill bottles, rest, and soak in the serenity of the surroundings.',
      'Kedarkantha Base Camp: After a steady climb of a few hours, you pass Kedarkantha Base Camp — a wide-open meadow nestled at the foot of the peak. The campsite offers breathtaking panoramic views of the surrounding mountains, especially at sunset when the sky turns golden and the peaks glow in soft hues.',
      'Juda Ka Talab: The trail continues through forests and meadows until you reach Juda Ka Talab, one of the most scenic campsites on the trek. This small alpine lake is surrounded by pine trees and open grasslands. In winter, it often freezes over; in summer, its clear waters beautifully reflect the surrounding peaks. With Kedarkantha Peak standing tall in the backdrop, this campsite offers a truly magical experience.',
      'Mountain views: From Juda Ka Talab, Kedarkantha Peak feels much closer, building excitement for the summit ahead. Crisp mountain air, starlit skies at night, and the peaceful atmosphere create the perfect Himalayan camping experience.',
      'The trek from Sankri to Juda Ka Talab is admired for its natural beauty and moderate difficulty — ideal for both beginners and seasoned trekkers. The trail passes through dense forests, open meadows, and occasional clearings with glimpses of snow-capped peaks.',
      'While the route is well established, it is always advisable to trek with a guide or in a group. Mountain weather can change quickly, and an experienced local guide ensures both safety and a richer experience — sharing insights about the flora, fauna, and culture of the region while helping you navigate the trail with ease.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '9,000 ft (Juda Ka Talab)',
    distance: '5 km',
    duration: '4–5 hrs',
  },
  {
    day: 3,
    title: 'From Juda Ka Talab to Kedarkantha Base Camp trek',
    description: [
      'Trek distance: 3 km · Duration: 2–3 hours · Mode: on foot · Altitude: Kedarkantha Base Camp, 3,200 m (11,250 ft) · Night stay: twin-share camp tents.',
      'The trek from Juda Ka Talab to Kedarkantha Base Camp is a crucial part of the Kedarkantha journey in Uttarakhand. It offers amazing views of the Himalayan landscape. Here is an overview of the route and what you can expect along the way.',
      'Juda Ka Talab: Your day begins at Juda Ka Talab (9,000 ft), a stunning alpine lake surrounded by meadows and tall pine forests. The clear, still waters often mirror the surrounding peaks, creating a picture-perfect and peaceful setting. Take a moment to enjoy the quiet beauty of this unique campsite before moving ahead.',
      'Gradual ascent: From Juda Ka Talab, the trail to Kedarkantha Base Camp involves a steady but gradual climb. The path winds through open meadows and thick forests — in winter, often blanketed with fresh snow. Proper footwear and trekking poles are essential here for balance and safety.',
      'Views of Kedarkantha Peak: As you gain altitude, Kedarkantha Peak appears more frequently on the horizon. Its snow-clad summit becomes an inspiring sight and a constant reminder of the goal ahead.',
      'Pine forests and meadows: The trail alternates between dense pine forests and vast meadows. In snowy conditions, the forests look enchanting — tall, snow-dusted trees lining the trail like a fairytale setting.',
      'Mountain vistas: Throughout the trek, views keep opening up to reveal spectacular Himalayan ranges. On clear days, you can spot the Swargarohini peaks, Bandarpoonch, Black Peak, and the Gangotri–Yamunotri ranges. These vistas grow even more captivating as you climb higher.',
      'Kedarkantha Base Camp: After a few hours of trekking, you reach Kedarkantha Base Camp (11,250 ft). This wide meadow is surrounded by towering peaks and offers 360° Himalayan views. The peak itself stands prominently in front of you — an ideal spot to rest, acclimatize, and prepare for the final summit push.',
      'Snow in winter: If you are trekking in winter, the trail and campsite are often covered in snow, turning the base camp into a magical white wonderland. While it adds a layer of challenge, it also enhances the beauty and thrill of the experience.',
      'Kedarkantha Base Camp is a favorite overnight halt before the summit push. Nestled in a wide meadow with stunning views of surrounding peaks, it offers the perfect setting to rest and acclimatize. Crisp mountain air, starlit skies, and the calm, quiet atmosphere make it an ideal place to recharge for the exciting summit climb the next morning.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '11,250 ft (Base Camp)',
    distance: '3 km',
    duration: '2–3 hrs',
  },
  {
    day: 4,
    title: 'Kedarkantha Base Camp to Summit and descent to Hargaon Thach',
    description: [
      'Trek distance: 11 km · Duration: 7–8 hours · Mode: on foot · Altitude: Hargaon Thach, 2,645 m (8,675 ft) · Night stay: twin-share camp tents.',
      'Summit day: Today is the highlight of your trek. Wake up early around 3:30 AM and begin your climb to the Kedarkantha summit. The trail is steep but rewarding, and reaching the top just in time for sunrise is an unforgettable experience. As the first rays of the sun light up the snow-covered peaks, the 360° Himalayan panorama leaves every trekker spellbound. Watching the golden sunrise from the summit is a moment that stays with you forever.',
      'The Kedarkantha Summit is the final destination of the trek, offering breathtaking 360° views of the surrounding Himalayan ranges. The route from Kedarkantha Base Camp involves a steady ascent through meadows and snowy ridges, gradually leading to the steep final climb. Once at the top, trekkers are rewarded with a panoramic sight of Swargarohini, Bandarpoonch, Black Peak, and the Gangotri–Yamunotri ranges — the most memorable moment of the entire journey.',
      'Starting from Kedarkantha Base Camp: The final ascent begins from the high-altitude meadow of Kedarkantha Base Camp (11,250 ft) — the launching point for the most awaited part of the trek.',
      'Early start: To witness the magical sunrise, trekkers usually begin the climb well before dawn (around 3:00–3:30 AM). Starting early also ensures firmer snow underfoot and clearer skies.',
      'Ascent through alpine meadows: The initial section is a gradual climb across wide alpine meadows. As you move higher, the terrain opens up and the path alternates between rocky patches and stretches of snow.',
      'Snow-clad terrain (in winter): During winter, the route remains blanketed in thick snow, making the ascent both challenging and enchanting. Trekking poles and proper footwear are especially important here for stability.',
      'Expansive mountain views: With every step higher, the horizon expands. Majestic Himalayan peaks such as Swargarohini, Bandarpoonch, Kalanag (Black Peak), and parts of the Gangotri–Yamunotri ranges reveal themselves. The closer you get to the summit, the more awe-inspiring the views become.',
      'Kedarkantha Summit (12,500 ft): After a few hours of climbing, you stand atop the snow-clad Kedarkantha summit. A 360° panorama of the Garhwal Himalayas unfolds before you. On one side lies the grandeur of the Swargarohini and Bandarpoonch ranges; on the other, the Har Ki Dun Valley stretches out beautifully below. The shrine at the summit and the golden glow of sunrise together make this the most unforgettable moment of the trek.',
      'The Kedarkantha summit, standing tall at around 12,500 ft (3,800 m), is famed for its breathtaking 360° panoramic views of the Himalayas and valleys below. It is one of the most cherished spots for trekkers — especially at sunrise, when the first rays paint the snow-clad peaks in shades of gold and orange.',
      'After celebrating at the summit, descend through forest trails and meadows to Hargaon Thach — your campsite for the night. The long day ends with a well-earned dinner and rest under starlit skies.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '12,500 ft (summit)',
    distance: '11 km',
    duration: '7–8 hrs',
  },
  {
    day: 5,
    title: 'Hargaon Thach to Sankri — Drive to Dehradun',
    description: [
      'Trek distance: 4.5 km (2–3 hrs) + 190 km drive Sankri to Dehradun · Mode: on foot, then Tempo Traveller.',
      'This morning, enjoy a hearty breakfast at your final campsite. After packing up, begin your descent from Hargaon to Sankri. The trail is easier downhill and takes you through beautiful forest clearings and scenic viewpoints. As you get closer to Sankri, you\'ll pass charming apple orchards before reaching the village — marking the end of your unforgettable Kedarkantha journey.',
      'Hargaon campsite: Your final day of trekking begins at Hargaon (8,500 ft), a peaceful campsite nestled in dense forests. Quiet surroundings, chirping birds, and rustling leaves create a soothing farewell to the mountains.',
      'Descend through forests: The trail from Hargaon to Sankri is mostly a descent through thick pine and oak forests. Unlike the alpine meadows higher up, this section offers a different charm — tall trees lining the path and cool shade throughout.',
      'Mountain views: Even on the way down, you\'ll catch occasional glimpses of snow-covered Himalayan peaks through openings in the forest. Sunlight and shadow filtering through the trees add to the beauty of this stretch.',
      'Passing through villages: As you near Sankri, the forest gradually gives way to villages and terraced fields. Simple wooden houses, apple orchards, and friendly locals offer a glimpse into the traditional lifestyle of the region.',
      'Sankri — trek ends: Your journey concludes as you arrive back in Sankri (6,400 ft), the quaint Himalayan village where the adventure began. Surrounded by lush green landscapes and snow-clad peaks, Sankri is the perfect place to celebrate the completion of your Kedarkantha trek.',
      'Departure from Sankri: Enjoy your last breakfast with the Indian Treks team at Sankri. After a certificate distribution ceremony and memorable group photos, it\'s time to bid farewell to the mountains.',
      'Indian Treks arranges transport from Sankri to Dehradun Railway Station, departing around 11:30 AM. The drive takes you through the same scenic valleys and villages, with expected arrival at Dehradun between 9:00–10:00 PM.',
      'With hearts full of memories and new friendships, your Kedarkantha trek with Indian Treks comes to a close.',
    ].join('\n\n'),
    meals: 'Breakfast',
    altitude: '6,400 ft (Sankri)',
    distance: '4.5 km trek + 190 km drive',
    duration: '2–3 hrs trek + 8–9 hrs drive',
  },
];
