import type { TrekTestimonial } from '@/lib/content/treks/types';

export const KEDARKANTHA_TESTIMONIALS: TrekTestimonial[] = [
  {
    name: 'Dushant Kumre',
    text: 'The trekking experience was truly enjoyable and rewarding, offering a perfect blend of adventure, natural beauty, and personal challenge. The trail was well-planned, the scenery was breathtaking throughout, and the guides were supportive and knowledgeable, ensuring safety and motivation at every step. Although the trek was physically demanding at times, the sense of accomplishment upon reaching key points made it worthwhile. Overall, it was a memorable experience that enhanced teamwork, built confidence, and created lasting memories.',
    platform: 'google',
    verifyUrl: 'https://maps.app.goo.gl/8CQUuLvwtksSWvzA7',
    posted: '8 months ago',
    rating: 5,
  },
  {
    name: 'Lakshya Rathore',
    text: 'It was the most amazing experience ever done — I trekked 12,500 feet height to Kedarkantha. The services were very good. The food was very tasty. Guides are very helpful; they help you reach the top no matter what happens and support you to complete the journey. They look after the small things with full compatibility. I made good friends and had a good moment — definitely worth every penny. Satish (guide), Saku, and Vijay helped me especially with taking the whole group together. Hats off to these guys and their energy level. Really appreciate the efforts they put in for each and every person. And at last, thanks to Indian Treks for making this happen for me and my friends. Peace out ✌️',
    platform: 'google',
    verifyUrl: 'https://maps.app.goo.gl/pC6G2hoed1gFz24x5',
    posted: 'a year ago',
    rating: 5,
  },
  {
    name: 'Subhash Paul',
    text: 'It is a wonderful experience to do a trek at Kedarkantha with Indian Treks. Following good notes: 1. Very friendly. 2. Food is nice (wow). 3. Helpful. 4. Low price but good service. 5. With very friendly guide Sanjay Rana. Suggested to do trek with Indian Treks.',
    platform: 'google',
    verifyUrl: 'https://maps.app.goo.gl/xkQ4TfrFP2AHoTKWA',
    posted: '8 months ago',
    rating: 5,
  },
  {
    name: 'Priyanka Mandal',
    text: 'Awesome experience with Indian Treks. They are very helpful and take care of each and everyone. Their food is also very good and the gaiters they provide are also very good — they properly showed their uses. They also show each viewpoint and give enough time to enjoy at the viewpoint. They are very professional at the same time very punctual.',
    platform: 'google',
    verifyUrl: 'https://maps.app.goo.gl/fxpfS88Se7ztzwn88',
    posted: 'a year ago',
    rating: 5,
  },
  {
    name: 'Mohan Siva',
    text: 'Amazing experience with Indian Treks. The amenities provided were very good and the guide (Ranaji) is very supportive and provided the required guidelines. Recommend everyone to experience this in a lifetime.',
    platform: 'google',
    verifyUrl: 'https://maps.app.goo.gl/YG1mN2tdaDsy7RUS8',
    posted: 'a year ago',
    rating: 5,
  },
  {
    name: 'Nithesh Kumar',
    text: 'It was my first trekking experience and with Indian Treks it was the most enjoyable and amazing experience. Since it was my first time to see live snowfall, this experience was amazing with the team. The trek leader was very supportive and was looking after every trekker individually. I recommend their team for a great trek. Thank you — Nithesh.',
    platform: 'google',
    verifyUrl: 'https://maps.app.goo.gl/prTuhFg5kaGqM7jW9',
    posted: 'a year ago',
    rating: 5,
  },
  {
    name: 'Arjit Saxena',
    text: 'The experience was very good with their team. Food and stay were amazing and staff was very supportive. Trek leader was very supportive and was looking after every trekker individually. I recommend their team for a great trek experience.',
    platform: 'google',
    verifyUrl: 'https://maps.app.goo.gl/gNzDWvWrQePN6Rhd6',
    posted: 'a year ago',
    rating: 5,
  },
  {
    name: 'Vanchinathan ReRa',
    text: 'We recently completed the Chandrashila trek with Indian Treks — one month on, it was adventurous, memorable, and overall a great experience. We had also done the Kedarkantha trek with them in November 2025, travelling with my spouse and our teenage child. Everything was well organised from start to finish, with smooth pick-up and drop from Rishikesh. Rental gear from the agency was reliable. Campsite food was simple, moderate, and tasty; campsites were scenic and peaceful. The Swiss tent at Sari Village was compact and clean. Safety and pacing were handled well — never any rushing, with enough time to enjoy the surroundings. Comfortable even for those without prior trekking experience.',
    platform: 'google',
    verifyUrl: 'https://maps.app.goo.gl/McSerhZdgzkgdxpw6',
    posted: '5 months ago',
    rating: 4,
  },
  {
    name: 'Gauri Walanju',
    text: 'It was a wonderful adventure, and Indian Treks offered excellent service. The staff had wealth of expertise — managing large groups and ensuring safety of individual trekkers.',
  },
  {
    name: 'Akshar Raval',
    text: 'The organisation for the hike was excellent. Indian Treks is very adaptable. The most memorable experience was getting endless hot gulab jamun.',
  },
  {
    name: 'RJ Rajesh',
    text: 'Our wonderful trek guide together with Sir Vijay Rana and Sir Vivek Rana made our walk easy throughout. Everything went smoothly. Thank you very much.',
  },
];
