import type { ItineraryDay } from '@/lib/content/treks/types';

/** Day-wise itinerary for Har Ki Dun — full 7-day programme. */
export const HAR_KI_DUN_ITINERARY: ItineraryDay[] = [
  {
    day: 1,
    title: 'Dehradun to Sankri — Start your journey towards a Himalayan paradise',
    description: [
      'Elevation: 6,400 ft / 1,950 m (Sankri) · Drive: ~220 km · Drive time: around 10 hours · Pickup: 6:00 AM, Prince Chowk, Dehradun · Overnight: Sankri guesthouse · Meals: Dinner included (breakfast and lunch not included).',
      'Dehradun to Sankri: Begin your path to a Himalayan haven. Trekkers are collected at 6:00 AM in a Tempo Traveller or similar vehicle from Prince Chowk, Dehradun. Arrival in Sankri is expected by about 5:00–6:00 PM.',
      'To reach on time, reserve an overnight bus or train from Delhi to Dehradun ISBT the night before. The road distance is about 220 km and takes roughly 10 hours as you gain altitude toward 1,950 m.',
      'After entering the Uttarkashi district through Mussoorie — the “Queen of the Hills” — and scenic Kempty Falls, the drive continues through Naugaon, Purola, Mori, and Netwar before reaching Sankri, the trek starting point. The route runs parallel to the Tons River through pine forests. After Mussoorie the landscape changes dramatically — deep gorges give way to pine-clad slopes filled with the scent of pinewood.',
      'We stop at a roadside inn for lunch at a convenient hour. Once you reach Purola, finish important calls and downloads — connectivity becomes erratic beyond here. Purola is also the last reliable ATM. In this stretch, BSNL is often the only workable network; JIO may work intermittently near Sankri. Small stores selling miscellaneous items and some trekking gear are available along the way and in Sankri.',
      'The final 20 km into Sankri are especially scenic. Shortly before the village you pass the Govind National Park checkpoint. Sankri is a charming Himalayan base for many Garhwal treks, with beautiful views of Mount Swargarohini. In winter, expect snow from Sankri itself.',
      'After freshening up at the guesthouse, you will have time to explore the nearby market. Trekking essentials, garments, and equipment are available in the Sankri bazaar for any last-minute needs before the trail begins.',
    ].join('\n\n'),
    meals: 'Dinner',
    altitude: '6,400 ft (Sankri)',
    distance: '220 km drive',
    duration: '≈10 hrs',
  },
  {
    day: 2,
    title: 'Sankri to Pauni Garaat via Taluka — Witness step farming in the Himalayas',
    description: [
      'Drive: Sankri → Taluka, 12 km / ~1 hour · Taluka: 7,200 ft (2,200 m) · Trek: Taluka → Pauni Garaat, 10 km / 5–6 hours · Pauni Garaat: 8,200 ft (2,500 m) · Altitude gain: ~1,800 ft (550 m) · Level: gentle incline with easy level walking · Packed lunch · Spring-water points · Overnight: riverside camp in Govind National Park.',
      'At 7:00 AM we leave Sankri for Taluka. The short drive brings the terrain up close — streams cutting across the path, stones underfoot on the jeep track, and gradually thickening forest. The drive takes around an hour.',
      'At Taluka the trek begins. The first stretch descends toward the banks of the Tons; with the river on your right, the trail levels into a walk through conifer forest until the first cemented bridge. About ten minutes in you cross a small mountain stream on that bridge, then continue about fifteen minutes more to a wooden bridge where a gentle slope leads down to the water — refill bottles here and carry on.',
      'The Tons corridor is excellent for Himalayan wildlife spotting, and in spring and summer colorful orchids appear along the banks. The shaded river stretch is ideal for photography.',
      'Around 1:00 PM we cross the Supin tributary and pause at a lunch rest area. One of several trail-side food shacks sits on a rocky cliff above the rivulet — packaged snacks, hot bites, and drinks add a welcome twist alongside the packed lunch.',
      'Further on, corn, millet, and potato fields open out, giving the valley a ranch-like feel. The verdant step farming of Himalayan hamlets is a highlight of this day.',
      'Late afternoon you reach Pauni Garaat — a verdant clearing on the banks of the Supin at its most vibrant — as the sun begins to set. Welcome to the first camp of the trek.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '8,200 ft (Pauni Garaat)',
    distance: '12 km drive + 10 km trek',
    duration: '5–6 hrs trek',
  },
  {
    day: 3,
    title: 'Pauni Garaat to Kalkattiyadhar — Pass by a 300-year-old village',
    description: [
      'Elevation: 9,850 ft / 3,000 m (Kalkattiyadhar) · Trek: 8 km / 5–6 hours · Altitude gain: ~1,650 ft (500 m) · Packed lunch · Spring-water points · Level: balanced level walks and steeper inclines than Day 2 · Overnight: forest meadow camp near a food stand with mountain views.',
      'After breakfast around 6:00 AM, begin the 8 km journey from Pauni Garaat to Kalkattiyadhar (about six hours on trail). Through dense coniferous woodland the path reaches Seema — a cluster of concrete buildings and a forest-department guest house on the banks of the Supin. Across the river sits Osla. The hanging Seema Bridge over the Supin, with snow peaks behind it, is one of the best photo stops of the day.',
      'The trail passes three “garaat” — hydro-powered chaffing mills where locals separate millet and maize husks before grinding flour. Harvest plains, grazing cattle, and slant-roofed granaries keep a village atmosphere. Amaranth stands out especially in monsoon, when leaves turn reddish against the green slopes.',
      'About thirty minutes into the climb, Swargarohini and Mount Bandarpoonch open into view. Osla sits between cashew and walnut forests. Local lore links the village with devotion to Duryodhan of the Kauravas, and a temple in his honour still shapes local worship. The settlement also holds dwellings and the Someshwar temple — distinctive wooden architecture said to reach back many centuries. Villagers are hospitable and dress in traditional style; the main pooja is performed monthly when the village’s ritual head visits. After a short conversation with locals, continue climbing.',
      'Above Osla the trail steepens, with views toward the Dhauladhar Range and distant approaches toward Baspa Valley and Borasu Pass. The high path then eases onto Kalkattiyadhar — a tabletop green meadow, the second overnight camp of the trek. Wide views take in Bugyal Devsu, Black Peak, the Ruinsara Range, and Kedarkantha on the left. Rest well and prepare for the valley / summit push the next day.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '9,850 ft (Kalkattiyadhar)',
    distance: '8 km',
    duration: '5–6 hrs',
  },
  {
    day: 4,
    title: 'Kalkattiyadhar to Har Ki Dun and back — Summit day',
    description: [
      'Elevation: 11,800 ft / 3,600 m (Har Ki Dun) · Trek: 10 km / 8–9 hours (out and back) · Packed lunch · Spring-water points · Level: leisurely woodland walking with some boulder sections and mixed-gradient ascent · Overnight: return to Kalkattiyadhar forest meadow camp · Peaks: Swargarohini, Hata Peak, Black Peak.',
      'Today is the longest trekking day, so the group starts earlier than usual. As soon as breakfast is finished, begin the hike from Kalkattiyadhar toward Har Ki Dun — and prepare for scenery that outdoes the days before.',
      'The trail enters the glacier basin of alpine meadows and moraines. Towering pines line the way. From the Ruinsara side, the path climbs above the confluence of the Supin and its feeder streams; mountain views open steadily from here.',
      'Toward the Har Ki Dun Valley the trail mixes mild and steeper ascents. Higher up you may see snow patches and ice waterfalls — in winter these stretches hold heavy snow. The valley itself is a divine amphitheatre: glacial moraines, coniferous forest, ice streams, meadows, and the massifs of Swargarohini, Hata Peak, and Black Peak all at once.',
      'Although much of the grade is manageable, sections can approach a steep pitch and become harder under snow. The final approach climbs beside a river through thick trees to the high point of Har Ki Dun. From the top, take in Swargarohini I, Hata Peak, and Black Peak — pause long enough to absorb the Valley of Gods before retracing the trail.',
      'Return the same way to Kalkattiyadhar by late afternoon or evening. Camp again by the meadow food stand with mountain views, rest well, and prepare for the descent days ahead.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '11,800 ft (Har Ki Dun)',
    distance: '10 km (out & back)',
    duration: '8–9 hrs',
  },
  {
    day: 5,
    title: 'Kalkattiyadhar to Pauni Garaat via Osla — Retreating back',
    description: [
      'Elevation: 8,200 ft / 2,500 m (Pauni Garaat) · Trek: 8 km / ~5 hours · Altitude loss: ~1,650 ft (500 m) · Packed lunch · Spring-water points · Overnight: riverside camp in Govind National Park.',
      'From here the route truly turns downhill. Today you retrace the trail to Pauni Garaat, passing through Osla — another chance to share quiet moments with the villagers before bidding farewell to them and the high valley.',
      'Rise early at Kalkattiyadhar for a stunning sunrise over the meadow camp. In winter, nights sit below freezing while mornings often feel crisp and mild once the sun clears the ridge.',
      'Follow the same path you climbed on Day 3. The steady descent is comparatively easy — take your time and enjoy the changing views as altitude drops toward the Supin.',
      'Spend part of the day exploring Osla. Visit the Someshwar temple dedicated to Lord Shiva; the walls carry fine carved detail. After the village stop, continue down to the Pauni Garaat riverside campsite.',
      'Camp again by the river in Govind National Park. Savor a final night of mountain quiet under the stars before the exit trek toward Taluka and Sankri.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '8,200 ft (Pauni Garaat)',
    distance: '8 km',
    duration: '≈5 hrs',
  },
  {
    day: 6,
    title: 'Pauni Garaat to Sankri via Taluka — Last day of trekking',
    description: [
      'Elevation: 6,400 ft / 1,950 m (Sankri) · Trek: Pauni Garaat → Taluka, 10 km / ~5 hours · Drive: Taluka → Sankri, 12 km / ~1 hour · Packed lunch · Spring-water points · Overnight: Sankri guesthouse.',
      'This morning begins the final trail day — a five-hour descent to Taluka on the well-travelled path, with stops at familiar rest areas. After breakfast, follow the same corridor you walked on Day 2, now heading downhill toward Taluka.',
      'Along the walk, watch for “bicchu ghas” (stinging nettle) — even a light touch can sting for about twenty-five minutes. The plant is not poisonous, and locals even prepare food from it, but give it a wide berth on the trail.',
      'After a few hours you rejoin the Supin River corridor. The last stretch into Taluka follows a cemented path before the road-head. From Taluka, a one-hour jeep ride covers the remaining 12 km to Sankri.',
      'Check in at the Sankri guesthouse, freshen up, and enjoy a hot meal back in the base village. Network and market access return here — a fitting end to the trekking section before tomorrow’s drive to Dehradun.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '6,400 ft (Sankri)',
    distance: '10 km trek + 12 km drive',
    duration: '≈5 hrs trek + 1 hr drive',
  },
  {
    day: 7,
    title: 'Sankri to Dehradun — Saying goodbye to the mountains',
    description: [
      'Drive: Sankri → Dehradun Station · Distance: 220 km · Timing: depart ~7:00 AM, arrive ~6:00 PM · Duration: ≈10 hours · Vehicle: Tempo Traveller or similar · Meals: breakfast and lunch not included.',
      'With many fond memories, we say goodbye to the mountains today. The 10-hour drive from Sankri to Dehradun marks the end of the Har Ki Dun journey. Board after an early start around 7:00 AM and retrace the Tons-valley road via Netwar, Mori, Purola, Naugaon, and Mussoorie.',
      'Stop for breakfast and lunch at roadside inns along the way (cost on your own). You will be dropped at Dehradun railway station in a Tempo Traveller or comparable vehicle, typically around 6:00 PM — well timed for overnight travel toward Delhi.',
      'For onward buses, aim to leave Dehradun Bus Stand by about 9:00 PM to allow buffer for any road delays. The trek concludes at the Dehradun drop — thank you for walking the Valley of Gods with Indian Treks.',
    ].join('\n\n'),
    meals: 'Not included',
    altitude: 'Dehradun (~2,100 ft)',
    distance: '220 km drive',
    duration: '≈10 hrs (7 AM–6 PM)',
  },
];
