import type { ItineraryDay } from '@/lib/content/treks/types';

/** Day-wise itinerary for Kuari Pass — shown in the trek detail accordion. */
export const KUARI_PASS_ITINERARY: ItineraryDay[] = [
  {
    day: 1,
    title: 'Pickup from Rishikesh and drive to Joshimath',
    description: [
      'Altitude: ~2,089 ft (Rishikesh) to ~6,750 ft / 2,050 m (Joshimath) · Drive distance: ~256–280 km · Drive duration: 9–10 hours · Overnight: Hotel Dhaneesh, Joshimath (twin sharing) · Pickup: Tapovan–Badrinath Road & Railway Station area.',
      'Indian Treks picks you up from Rishikesh at 6:30 AM in a Bolero or similar vehicle (cost included in the package). Along the way you can stop for breakfast and lunch at local dhabas or restaurants (meals not included in the package).',
      'The drive from Rishikesh to Joshimath is long but incredibly scenic. As the road winds along the Alaknanda River and through the Garhwal Himalayas, you pass charming mountain towns, lush valleys, and views that set the tone for the adventure ahead.',
      'Journey from Rishikesh to Joshimath: Your adventure begins in Rishikesh, the official starting point of the trek. Pickup is arranged in Rishikesh, then we follow the scenic Badrinath Highway toward Joshimath.',
      'Rishikesh itself is worth exploring. If time allows, plan a short stay before or after the trek for its spiritual charm, yoga culture, river rafting, and Ganga Aarti at the ghats.',
      'The drive to Joshimath (2,050 m / 6,750 ft) takes nearly 10 hours and covers around 256–280 km. Though long, the road is filled with spectacular views. The Alaknanda accompanies you almost throughout, growing more dramatic as you climb higher into the Himalayas.',
      'One of the highlights of this road trip is crossing the Panch Prayag — the five sacred confluences where tributaries join the Alaknanda / Ganga system:',
      'Devprayag — where Bhagirathi meets Alaknanda.',
      'Rudraprayag — where Mandakini merges with Alaknanda.',
      'Karnaprayag — where Pindar joins Alaknanda.',
      'Nandaprayag — where Nandakini flows into Alaknanda.',
      'Vishnuprayag — where Dhauliganga meets Alaknanda.',
      'Each Prayag is spiritually significant and scenic. Keep your camera ready, stay awake on the highway stretches, and soak in every moment of this drive into the mountains.',
      'Arrive Joshimath by evening, check in at Hotel Dhaneesh (twin sharing), freshen up, and attend a short trek briefing with the Indian Treks team. Overnight stay in Joshimath.',
    ].join('\n\n'),
    meals: 'Dinner',
    altitude: '6,750 ft (Joshimath)',
    distance: '256–280 km drive',
    duration: '9–10 hrs',
  },
  {
    day: 2,
    title: 'Joshimath to Dhak by drive and to Gulling Top by trek',
    description: [
      'Altitude: ~7,545 ft → ~8,530 ft → ~9,264 ft (Gulling Top, ~2,900 m) · Trek distance: 3 km · Trek duration: 3–4 hours · Difficulty: Easy to Moderate · Overnight: Gulling Top Campsite (twin sharing).',
      'A series of ice-capped mountains greets you in Joshimath, looking even more inviting than at the dawn of the journey. After an early breakfast, the group sets off for Dhak Village — about 12 km away in Joshimath Tehsil, a drive of roughly 45 minutes. This is where the trek begins.',
      'From Dhak, the trail steadily ascends, leaving the road and climbing toward Tugasi village. The dirt path includes a few sharp T-turns before easing onto flatter ground, then gentle rising slopes. The terrain is generally rugged, with terraced fields and rocky outcrops. Greenery can be sparse, but panoramic views of the Garhwal Himalayas unfold in all directions.',
      'Keep an eye out for the shimmering Dhauliganga River deep below, and the massive Vishnugad–Tapovan hydroelectric station along the valley. Unlike higher camps, you will not find deep snow on this stretch — yet the landscapes are equally captivating.',
      'After about 20–25 minutes of trekking, you reach Kharchi village, where trekkers can refill bottles and take a short break. The trail then continues with steep switchbacks until Lower Tugasi, before splitting in two. Indian Treks follows the route alongside a traditional hydro-powered flour mill into Upper Tugasi — a charming hamlet of wheat fields, flower patches, thatched-roof houses, and mountain streams.',
      'From here the trail climbs gradually, leaving farmland behind, and soon reveals the first stunning view of Mount Dronagiri (7,066 m) rising sharply in the distance — a sight that sets the tone for the days ahead.',
      'By afternoon you reach Gulling Top Campsite (~2,900 m), nestled in open meadows surrounded by oak and rhododendron forests. After settling in, enjoy a hot lunch at camp. The evening is free to relax, soak in the mountain quiet, and admire snow-covered slopes around you. Adventurous trekkers may join the trek leader for a short hike to the Gulling Top viewpoint for closer glimpses of the icy forests.',
      'As dusk falls, prepare for a night under the stars. The highlight awaits at dawn — when the first rays of sunlight strike Dronagiri peak, painting it gold and crimson, right from your campsite.',
      'Overnight stay in twin-sharing tents at Gulling Top.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '9,264 ft (Gulling Top)',
    distance: '12 km drive + 3 km trek',
    duration: '3–4 hrs trek',
  },
  {
    day: 3,
    title: 'Trek from Gulling Top to Tali Forest Camp',
    description: [
      'Altitude: ~9,264 ft → ~11,014 ft (Tali Forest Camp, ~3,350 m) · Trek distance: 5.5 km · Trek duration: 8–9 hours · Difficulty: Easy to Moderate · Overnight: Tali Forest Camp (twin sharing).',
      'Today’s trail takes you deeper into the wilderness, with a steady ascent from Gulling Top to Tali Forest Camp (3,350 m). Compared with the steeper climb of the previous day, the slopes are gentler and the walk more pleasant — a welcome change of pace.',
      'The trail winds through enchanting forests of rhododendron, oak, and walnut. In late March, the rhododendrons bloom in brilliant shades of pink and white, adding a magical charm to the trek. The dense forest canopy, the earthy fragrance of leaves, and the quiet rustling of the woods create an almost mystical atmosphere.',
      'About 20 minutes into the hike, the trees part to reveal a wide green meadow overlooking the majestic snow-covered ranges — a perfect spot to rest, take photos, and soak in the grandeur of the Himalayas before continuing. From here, a small stream crossing leads you back into a mixed forest of rhododendrons and conifers, gradually thickening as you gain altitude.',
      'In winter, this entire stretch transforms into a snow wonderland, with thick blankets of snow draped over oak and conifer trees, turning the trail into a dreamy white corridor.',
      'By afternoon you reach Tali Forest Camp, set amidst dense woods with views that open toward the iconic Hathi–Ghoda peaks and the ever-dominant Dronagiri standing proudly to your right.',
      'Enjoy a hot lunch at the campsite and spend the evening in the serene lap of nature. This forest clearing is a magical place for stargazing at night, with the silhouettes of snowy peaks in the backdrop.',
      'Overnight stay in twin-sharing tents at Tali.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '11,014 ft (Tali Forest Camp)',
    distance: '5.5 km trek',
    duration: '8–9 hrs',
  },
  {
    day: 4,
    title: 'Trek from Khullara to Kuari Pass summit and descend back to Khullara',
    description: [
      'Altitude: ~11,014 ft → ~12,516 ft (Kuari Pass) → ~11,014 ft · Trek distance: 8 km · Trek duration: 8–9 hours · Difficulty: Moderate · Overnight: Khullara Campsite (twin sharing).',
      'Today is the most awaited day of the Kuari Pass trek — the summit climb. The group starts early from Khullara campsite, at the base of Kuari Pass, to make the most of clear skies and crisp morning views.',
      'Khullara to Kuari Pass summit: The trail begins with a gradual but steady climb through alpine meadows, rocky sections, and occasional snow patches (depending on the season). As you gain altitude, every step rewards you with expanding Himalayan vistas.',
      'Reaching Kuari Pass (4,264 m / 12,516 ft) is a breathtaking moment. From here, a 360° panorama of the Garhwal Himalayas unfolds — dominated by towering snow-capped giants:',
      'Nanda Devi (7,816 m) — the highest peak entirely in India, revered as the “Goddess of Bliss.”',
      'Kamet (7,756 m) — the second-highest peak in Garhwal, with its striking pyramid shape.',
      'Dronagiri (7,066 m) — steeped in mythology and known for its sheer beauty.',
      'Chaukhamba (7,138 m) — a magnificent massif of four peaks, often called the “Four Pillars.”',
      'Hathi Parvat (6,727 m) — resembling an elephant, standing tall in grandeur.',
      'Ghori Parbat (6,708 m) — another mighty peak, adding to the spellbinding skyline.',
      'The view from Kuari Pass is considered one of the finest Himalayan panoramas in India. Spend time here soaking in the sight, capturing photographs, and experiencing the stillness of the high mountains.',
      'Return to Khullara: After the summit, retrace your steps down toward Khullara campsite. The descent is easier and gives another chance to admire the rolling meadows, alpine ridges, and forested valleys.',
      'Before returning to camp, stop at the Khullara Viewpoint for another stunning perspective of the mountains and valleys — especially at sunset, when the peaks glow in warm hues.',
      'Evening is spent resting at camp, reflecting on the unforgettable summit experience. Overnight stay in twin-sharing tents at Khullara.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '12,516 ft (Kuari Pass)',
    distance: '8 km trek',
    duration: '8–9 hrs',
  },
  {
    day: 5,
    title: 'Trek from Khullara to Tugasi road head and drive to Joshimath',
    description: [
      'Altitude: ~11,014 ft → ~8,530 ft → ~7,545 ft · Trek distance: 8.5 km · Trek duration: 6–7 hours · Drive: ~15 km / 30 minutes–1 hour · Overnight: Hotel in Joshimath (twin / triple sharing).',
      'After breakfast, begin the final descent from Khullara campsite toward Tugasi Village. The trail is mostly downhill, winding through alpine meadows, terraced fields, and oak–rhododendron forests. Though easier than the ascent, the long 8.5 km descent can still be demanding on the knees — trekking poles are helpful.',
      'On the way, enjoy the last glimpses of the Garhwal Himalayas — views of Dronagiri, Hathi–Ghoda, and the surrounding ridges gradually fade as you descend into the valley. After about 6–7 hours of trekking, you reach Tugasi Village, the endpoint of the trek.',
      'Vehicles wait at the road head to drive you back to Joshimath (~15 km, ~30–45 minutes). The drive is short but scenic, with river valleys, forested slopes, and distant snowy peaks. If time permits, stop at viewpoints along the way for quick photographs.',
      'By evening you settle in Joshimath, marking the end of the Kuari Pass trekking adventure. Overnight stay in a guesthouse / hotel at Joshimath (twin / triple sharing).',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '7,545 ft (Joshimath)',
    distance: '8.5 km trek + 15 km drive',
    duration: '6–7 hrs trek + drive',
  },
  {
    day: 6,
    title: 'Depart from Joshimath to Dehradun via Rishikesh',
    description: [
      'Altitude: ~8,530 ft → ~2,089 ft · Drive distance: ~280 km · Drive duration: 9–10 hours · Drop-off: Tapovan–Badrinath Road & Railway Station (Indian Treks).',
      'Route: Joshimath → Nandaprayag → Karnaprayag → Rudraprayag → Srinagar (Garhwal) → Devprayag → Rishikesh → Dehradun.',
      'Wake up to your last breakfast with Indian Treks at Joshimath. After an early meal, the group departs by 6:00 AM for the return journey. Lunch is taken en route, and you are expected to reach Rishikesh / Dehradun by evening (around 6–7 PM).',
      'The drive from Joshimath to Rishikesh is long but spectacular. The road meanders along the Alaknanda River, passing through quaint Himalayan towns such as Chamoli and Devprayag, where the Bhagirathi and Alaknanda merge to form the holy Ganga. The winding mountain roads offer countless views of deep valleys, rushing rivers, and terraced villages.',
      'To keep the journey comfortable, the convoy takes short halts at roadside dhabas for refreshments. Starting early helps avoid traffic congestion and ensures a smoother ride back.',
      'By evening you arrive in Rishikesh / Dehradun, carrying home unforgettable memories of the Kuari Pass trek. Trip concludes with drop-off at Tapovan–Badrinath Road and the railway station area.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch',
    altitude: '2,089 ft (Rishikesh / Dehradun)',
    distance: '280 km drive',
    duration: '9–10 hrs',
  },
];
