import type { ItineraryDay } from '@/lib/content/treks/types';

/** Day-wise itinerary for Kuari Pass — shown in the trek detail accordion. */
export const KUARI_PASS_ITINERARY: ItineraryDay[] = [
  {
    day: 1,
    title: 'Dehradun/Rishikesh to Joshimath | Base Camp',
    description: [
      'Route: Dehradun → Rishikesh → Devprayag → Srinagar → Rudraprayag → Karnaprayag → Nandaprayag → Joshimath',
      'Your Kuari Pass adventure begins with a scenic Himalayan drive towards Joshimath, the gateway and base camp for the trek. Trekkers joining IndianTreks can board from Rishikesh Natraj Chowk in the morning and begin the journey towards the Garhwal Himalayas.',
      'The route follows the beautiful Alaknanda River and passes through several important Himalayan towns and sacred river confluences. With mountain landscapes unfolding along the way, the drive itself becomes an exciting introduction to the trek.',
      'Key Highlights Along the Route:',
      'Devprayag: Witness the sacred confluence of the Alaknanda and Bhagirathi rivers, where the Ganga takes its name.',
      'Srinagar (Garhwal): A historic town situated along the Alaknanda River and an important stop on the journey.',
      'Rudraprayag: Located at the confluence of the Alaknanda and Mandakini rivers, surrounded by dramatic Himalayan landscapes.',
      'Karnaprayag: The meeting point of the Alaknanda and Pindar rivers, forming one of Uttarakhand\'s renowned Panch Prayag.',
      'Nandaprayag: A peaceful Himalayan town where the Alaknanda meets the Nandakini River.',
      'Joshimath: Arrive at the bustling mountain town that serves as the base for several major Himalayan treks.',
      'After reaching Joshimath, check in to the hotel, freshen up and relax after the long mountain drive. The evening can be used to rest and prepare for the upcoming trekking days.',
    ].join('\n\n'),
    meals: 'Dinner',
    altitude: '2,089 ft → 7,545 ft',
    distance: 'Approx. 280 km drive',
    duration: '9–10 hrs',
    overnight: 'Joshimath Hotel – Triple Sharing',
    pickup: 'Rishikesh Natraj Chowk',
    departure: 'Around 6:00–7:00 AM',
  },
  {
    day: 2,
    title: 'Joshimath to Tugasi Village & Trek to Gulling Campsite',
    description: [
      'After breakfast, the day begins with a short scenic drive from Joshimath to Tugasi Village, the starting point of your Kuari Pass trek. The approximately 15 km mountain drive takes you deeper into the Himalayan landscape, with traditional villages, forested slopes and panoramic mountain views along the way.',
      'On reaching Tugasi, the trek officially begins. The trail gradually climbs through beautiful Himalayan terrain towards Gulling Campsite, covering around 3 km.',
      'Trek from Tugasi to Gulling:',
      'The trail follows a gradual uphill route through forests and open mountain sections. As you gain altitude, the surroundings become increasingly scenic, with expansive views of the valleys and Himalayan peaks.',
      'The relatively short distance makes this a comfortable introduction to the trekking days ahead. However, the gradual altitude gain means trekkers should maintain a steady pace and stay hydrated.',
      'Gulling Campsite:',
      'Gulling is a beautiful campsite surrounded by the Himalayan wilderness. On reaching the campsite, settle in and take some time to relax and enjoy the peaceful mountain surroundings.',
      'If weather conditions are favourable, you can enjoy spectacular views from the campsite and experience the changing colours of the mountains around sunset.',
      'The evening will be used for rest, acclimatization and trek briefing before the more demanding sections of the Kuari Pass trail begin.',
      'Overnight stay at Gulling Campsite.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '7,545 ft → 8,530 ft → 9,264 ft',
    distance: 'Approx. 3 km trek',
    duration: '3–4 hrs',
    difficulty: 'Easy to Moderate',
    overnight: 'Gulling Campsite – Triple Sharing',
    drive: 'Joshimath → Tugasi · ~15 km by taxi',
  },
  {
    day: 3,
    title: 'Gulling Campsite to Khullara Campsite',
    description: [
      'After breakfast, begin your trek from Gulling Campsite towards Khullara, one of the most scenic sections of the Kuari Pass trail. Today’s route takes you gradually higher through dense Himalayan forests before opening into expansive alpine meadows.',
      'Through Himalayan Forests:',
      'The trail initially climbs steadily through beautiful forests of Oak, Rhododendron (Buransh) and Horse Chestnut. Depending on the season, the landscape changes dramatically. In spring, blooming rhododendrons add vibrant colour to the trail, while during winter, snow can remain on this forested section for longer periods.',
      'Take your time to enjoy the peaceful surroundings, listen to the forest and maintain a comfortable trekking pace as the altitude increases.',
      'First Himalayan Mountain Views:',
      'As the forest gradually becomes thinner, the trail begins to reveal impressive views of the Garhwal Himalayas. Among the prominent peaks visible from this section are:',
      'Dronagiri (7,066 m): A striking pyramid-shaped peak that dominates the surrounding skyline.',
      'Hathi Ghoda Parvat: A distinctive mountain formation known for its elephant-and-horse-like appearance.',
      'This is where the Kuari Pass experience truly starts to open up, with increasingly expansive mountain views replacing the dense forest.',
      'Entering the Alpine Bugyals:',
      'Further along the trail, the forest gives way to the spectacular alpine meadows, locally known as Bugyals. The scenery changes from dense green forest to wide-open mountain slopes.',
      'Depending on the season, these meadows may appear lush green, golden-brown or covered in snow. With fewer trees around, you can enjoy sweeping views across the surrounding valleys and Himalayan peaks.',
      'Khullara Campsite:',
      'After completing the day’s trek, arrive at Khullara Campsite, a beautiful meadow surrounded by some of the most impressive Himalayan scenery on the route.',
      'From the campsite, you can enjoy views towards the Dronagiri massif, Changabang and Kalanka. The open meadow provides an excellent setting to relax after the day’s trek.',
      'If the weather is clear, the evening can be especially memorable as the setting sun illuminates the snow-covered peaks, creating the famous golden-hour views of the Himalayas.',
      'Khullara is also strategically located for the next stage of the trek, serving as an important camping point before heading towards Kuari Pass and Tali Top.',
      'Overnight stay at Khullara Campsite.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '9,264 ft → 11,014 ft',
    distance: 'Approx. 5.5 km trek',
    duration: '8–9 hrs',
    difficulty: 'Easy to Moderate',
    overnight: 'Khullara Campsite – Triple Sharing',
  },
  {
    day: 4,
    title: 'Khullara to Kuari Pass & Return to Khullara',
    description: [
      'Today is the highlight of your Kuari Pass Trek. After an early breakfast, begin your trek from Khullara Campsite towards the Kuari Pass high point. The trail takes you across open alpine meadows, mountain ridges and rocky sections, with the landscape becoming increasingly dramatic as you gain altitude.',
      'The Ascent to Kuari Pass:',
      'The morning trek begins with a steady climb through the high-altitude terrain. Depending on the season and weather conditions, you may encounter snow-covered sections, rocky patches and exposed mountain trails.',
      'As you climb higher, the forest gradually disappears and the trail opens into vast alpine landscapes. The changing perspective reveals magnificent views of the surrounding Garhwal Himalayas, making the climb both challenging and rewarding.',
      'Reaching the Kuari Pass High Point:',
      'After several hours of trekking, reach the high point of the trail at approximately 12,516 ft. Take some time to rest, appreciate the incredible Himalayan surroundings and capture photographs.',
      'On a clear day, the panoramic mountain views can include spectacular Himalayan peaks and ranges such as Nanda Devi, Dronagiri, Kamet, Chaukhamba, Hathi Parvat and Ghori Parbat, depending on visibility and the exact viewpoint.',
      'This is the moment to pause and appreciate the scale and beauty of the Himalayas before beginning the descent.',
      'Descent Back to Khullara:',
      'After spending time at the high point, begin the descent towards Khullara Campsite, following the mountain trail back through the alpine meadows and ridges.',
      'The descent may feel easier than the ascent, but trekkers should remain careful on loose, rocky or snow-covered sections. Maintain a controlled pace and follow the instructions of the trek leader.',
      'On reaching Khullara, relax at the campsite and enjoy a well-earned evening in the mountains.',
      'Himalayan Views:',
      'One of the biggest highlights of today’s trek is the opportunity to witness some of the region’s most impressive Himalayan landscapes. With favourable weather, you may see:',
      'Nanda Devi – One of India’s most iconic Himalayan peaks.',
      'Dronagiri – A striking massif dominating the surrounding landscape.',
      'Kamet – A prominent high-altitude peak of the Garhwal Himalayas.',
      'Chaukhamba – A spectacular group of Himalayan peaks.',
      'Hathi Parvat – A distinctive mountain visible from sections of the trail.',
      'Ghori Parbat – Another prominent peak forming part of the surrounding Himalayan panorama.',
      'Please note: Mountain visibility depends heavily on weather, cloud cover and seasonal conditions.',
      'After completing the day’s trek, return to Khullara Campsite for dinner and overnight rest.',
      'Overnight stay at Khullara Campsite.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '11,014 ft → 12,516 ft → 11,014 ft',
    distance: 'Approx. 8 km trek',
    duration: '8–9 hrs',
    difficulty: 'Moderate',
    overnight: 'Khullara Campsite – Triple Sharing',
  },
  {
    day: 5,
    title: 'Khullara to Tugasi Village & Drive to Joshimath',
    description: [
      'After breakfast, begin your final trekking day with a gradual descent from Khullara Campsite towards Tugasi Village, the roadhead where the trek concludes.',
      'Descent from Khullara to Tugasi:',
      'The trail gradually loses altitude as you make your way back through the Himalayan landscape. The route passes through forested sections, mountain slopes and village trails, offering a different perspective of the terrain you experienced during the ascent.',
      'Although today’s route is mostly downhill, the distance is considerable. Maintain a comfortable pace and take regular short breaks, especially while navigating uneven or rocky sections.',
      'After approximately 8.5 km and 6–7 hours of trekking, you will reach Tugasi Village Roadhead, marking the completion of your Kuari Pass trekking experience.',
      'Drive from Tugasi to Joshimath:',
      'Once you reach Tugasi, our Indian Treks transport team will be ready to transfer you back to Joshimath.',
      'The approximately 15 km drive takes around 30 minutes to 1 hour, depending on road and weather conditions. Enjoy the final views of the surrounding mountains and valleys as you descend towards Joshimath.',
      'On arrival, check in to your hotel and take some well-deserved time to rest, freshen up and relax after completing the trek.',
      'The evening is free to explore the local market of Joshimath, purchase souvenirs or simply unwind with your fellow trekkers and share memories from the trail.',
      'Overnight stay at Joshimath Hotel.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch, Dinner',
    altitude: '11,014 ft → 8,530 ft → 7,545 ft',
    distance: 'Approx. 8.5 km trek',
    duration: '6–7 hrs',
    difficulty: 'Easy to Moderate',
    overnight: 'Joshimath Hotel – Triple/Quad Sharing',
    drive: 'Tugasi → Joshimath · ~15 km · 30–60 min',
  },
  {
    day: 6,
    title: 'Joshimath to Rishikesh/Dehradun | Trek Ends',
    description: [
      'Route: Joshimath → Nandaprayag → Karnaprayag → Rudraprayag → Srinagar → Devprayag → Rishikesh → Dehradun',
      'After breakfast, it is time to begin your journey back from Joshimath to Rishikesh and Dehradun, marking the end of your Kuari Pass adventure.',
      'Start early in the morning, around 6:00 AM, for the long scenic drive through the Garhwal Himalayas. The route follows the Alaknanda River and takes you through several picturesque mountain towns and valleys that you may have passed during your onward journey.',
      'Scenic Himalayan Drive:',
      'As you descend towards the lower Himalayan region, enjoy changing landscapes, winding mountain roads, river valleys and beautiful views of the surrounding mountains.',
      'The journey passes through important towns and landmarks including:',
      'Nandaprayag – The confluence of the Alaknanda and Nandakini rivers.',
      'Karnaprayag – Located at the confluence of the Alaknanda and Pindar rivers.',
      'Rudraprayag – Where the Alaknanda and Mandakini rivers meet.',
      'Srinagar (Garhwal) – A major town situated along the Alaknanda River.',
      'Devprayag – The sacred confluence of the Alaknanda and Bhagirathi rivers.',
      'Rishikesh – The gateway to the Garhwal Himalayas and the final major stop of the journey.',
      'A lunch break and short refreshment stops will be taken en route, depending on the group’s travel schedule and road conditions.',
      'Journey Completion:',
      'After approximately 9–10 hours of driving, reach Rishikesh Natraj Chowk, where the Kuari Pass trek journey officially concludes for trekkers opting for the Rishikesh drop.',
      'For trekkers continuing to Dehradun, the vehicle will proceed onwards after the Rishikesh drop.',
      'Take home not just photographs, but the memories of alpine meadows, Himalayan forests, high mountain trails and breathtaking Garhwal landscapes experienced along the Kuari Pass trail.',
      'Trek ends with beautiful memories of the Himalayas.',
    ].join('\n\n'),
    meals: 'Breakfast, Lunch',
    altitude: '7,545 ft → 2,089 ft',
    distance: 'Approx. 280 km drive',
    duration: '9–10 hrs',
    dropoff: 'Rishikesh Natraj Chowk',
    departure: 'Around 6:00 AM',
  },
];
