import type { GeoLocation } from './types';

/**
 * Verified geographic coordinates used by trek route maps.
 * Sources:
 * - openstreetmap-nominatim: OpenStreetMap Nominatim API (ODbL), queried Aug 2026
 * - himalaya-trekker-gps: Published trek-operator GPS for Kedarkantha summit
 * - authoritative-reference: Commonly cited coordinates for named peaks/temples
 */
export const LOCATIONS: Record<string, GeoLocation> = {
  'dehradun-railway': {
    key: 'dehradun-railway',
    name: 'Dehradun Railway Station',
    lng: 78.0335416,
    lat: 30.3125021,
    elevationM: 640,
    source: 'openstreetmap-nominatim',
    description: 'Main railhead for Garhwal treks — overnight trains from Delhi connect here for same-day road transfers toward Sankri.',
  },
  vikasnagar: {
    key: 'vikasnagar',
    name: 'Vikasnagar',
    lng: 77.9065,
    lat: 30.4694,
    elevationM: 430,
    source: 'openstreetmap-nominatim',
  },
  barkot: {
    key: 'barkot',
    name: 'Barkot',
    lng: 78.205961,
    lat: 30.808606,
    elevationM: 1291,
    source: 'openstreetmap-nominatim',
  },
  naugaon: {
    key: 'naugaon',
    name: 'Naugaon',
    lng: 78.13339,
    lat: 30.78644,
    elevationM: 1100,
    source: 'openstreetmap-nominatim',
  },
  nainbag: {
    key: 'nainbag',
    name: 'Nainbagh',
    lng: 78.0050535,
    lat: 30.5704875,
    elevationM: 1200,
    source: 'openstreetmap-nominatim',
  },
  netwar: {
    key: 'netwar',
    name: 'Netwar',
    lng: 78.1029342,
    lat: 31.0661826,
    elevationM: 1550,
    source: 'openstreetmap-nominatim',
  },
  mussoorie: {
    key: 'mussoorie',
    name: 'Mussoorie',
    lng: 78.0782906,
    lat: 30.4569012,
    elevationM: 2005,
    source: 'openstreetmap-nominatim',
    description: 'Hill station on the Dehradun–Sankri drive corridor — common breakfast and fuel stop before the Tons valley descent.',
  },
  'kempty-falls': {
    key: 'kempty-falls',
    name: 'Kempty Falls',
    lng: 78.0364,
    lat: 30.4842,
    elevationM: 1390,
    source: 'openstreetmap-nominatim',
  },
  purola: {
    key: 'purola',
    name: 'Purola',
    lng: 78.0831875,
    lat: 30.8786966,
    elevationM: 1524,
    source: 'openstreetmap-nominatim',
    description: 'Last major market town before Mori and Netwar on the Kedarkantha approach — last ATM and supplies for many groups.',
  },
  mori: {
    key: 'mori',
    name: 'Mori',
    lng: 78.0462478,
    lat: 31.0192118,
    elevationM: 1150,
    source: 'openstreetmap-nominatim',
  },
  sankri: {
    key: 'sankri',
    name: 'Sankri',
    lng: 78.1841131,
    lat: 31.078024,
    elevationM: 1950,
    source: 'openstreetmap-nominatim',
    description: 'Trailhead village for Kedarkantha — Forest Department check-post, homestays, and trek permit formalities start here.',
  },
  taluka: {
    key: 'taluka',
    name: 'Taluka',
    lng: 78.245793,
    lat: 31.0778208,
    elevationM: 2200,
    source: 'openstreetmap-nominatim',
    description: 'Last road-head for Har Ki Dun — jeep from Sankri (~12 km); trek begins along the Tons toward Pauni Garaat.',
  },
  'pauni-garaat': {
    key: 'pauni-garaat',
    name: 'Pauni Garaat',
    lng: 78.3055,
    lat: 31.1028,
    elevationM: 2500,
    source: 'project-itinerary',
    description: 'Riverside camp in Govind National Park on the Supin — Day 2 overnight after the Taluka forest walk.',
  },
  seema: {
    key: 'seema',
    name: 'Seema',
    lng: 78.3499378,
    lat: 31.1170286,
    elevationM: 2560,
    source: 'openstreetmap-nominatim',
    description: 'Forest-department guest house hamlet on the Supin — hanging bridge views toward Osla and Swargarohini.',
  },
  osla: {
    key: 'osla',
    name: 'Osla',
    lng: 78.3427722,
    lat: 31.1188962,
    elevationM: 2600,
    source: 'openstreetmap-nominatim',
    description: 'Historic wooden village across the Supin from Seema — Someshwar temple and traditional Garhwali architecture.',
  },
  kalkattiyadhar: {
    key: 'kalkattiyadhar',
    name: 'Kalkattiyadhar',
    lng: 78.392,
    lat: 31.133,
    elevationM: 3000,
    source: 'project-itinerary',
    description: 'Tabletop meadow camp at ~9,850 ft between Osla and Har Ki Dun — views of Swargarohini, Bandarpoonch and Black Peak.',
  },
  'juda-ka-talab': {
    key: 'juda-ka-talab',
    name: 'Juda Ka Talab',
    lng: 78.1843029,
    lat: 31.0524927,
    elevationM: 2773,
    source: 'openstreetmap-nominatim',
    description: 'Frozen alpine lake and first major camp on Day 2 — dense oak forest opens to meadow views toward Swargarohini.',
  },
  'kedarkantha-base': {
    key: 'kedarkantha-base',
    name: 'Kedarkantha Base Camp',
    lng: 78.1802171,
    lat: 31.0586527,
    elevationM: 3200,
    source: 'openstreetmap-nominatim',
    description: 'High meadow camp below the summit ridge — summit push typically starts pre-dawn for sunrise at the top.',
  },
  'kedarkantha-summit': {
    key: 'kedarkantha-summit',
    name: 'Kedarkantha Summit',
    lng: 78.1718771,
    lat: 31.0225687,
    elevationM: 3810,
    source: 'openstreetmap-trail',
    description: '360° winter summit at 12,500 ft — Swargarohini, Bandarpoonch, and Black Peak dominate the horizon on clear mornings.',
  },
  hargaon: {
    key: 'hargaon',
    name: 'Hargaon Thach',
    lng: 78.1800651,
    lat: 31.0581682,
    elevationM: 2645,
    source: 'openstreetmap-nominatim',
    description: 'Alternate descent meadow camp on the return leg — gentler knee-friendly route back toward Sankri.',
  },
  rishikesh: {
    key: 'rishikesh',
    name: 'Rishikesh',
    lng: 78.2916193,
    lat: 30.1086537,
    elevationM: 637,
    source: 'openstreetmap-nominatim',
    description:
      'Kuari Pass / Curzon Trail pickup (~2,089 ft) — Tapovan–Badrinath Road & Railway Station; also gateway for Chopta and Char Dham transfers.',
  },
  joshimath: {
    key: 'joshimath',
    name: 'Joshimath',
    lng: 79.5612607,
    lat: 30.5555752,
    elevationM: 2050,
    source: 'openstreetmap-nominatim',
    description:
      'Gateway town for Kuari Pass / Curzon Trail — overnight at ~2,050 m before the Dhak trailhead.',
  },
  karnaprayag: {
    key: 'karnaprayag',
    name: 'Karnaprayag',
    lng: 79.2156,
    lat: 30.2636,
    elevationM: 1450,
    source: 'openstreetmap-nominatim',
    description: 'Panch Prayag — confluence of Pindar and Alaknanda on the Rishikesh–Joshimath highway.',
  },
  nandaprayag: {
    key: 'nandaprayag',
    name: 'Nandaprayag',
    lng: 79.3256,
    lat: 30.3322,
    elevationM: 914,
    source: 'openstreetmap-nominatim',
    description: 'Panch Prayag — where Nandakini meets Alaknanda en route to Joshimath.',
  },
  vishnuprayag: {
    key: 'vishnuprayag',
    name: 'Vishnuprayag',
    lng: 79.575,
    lat: 30.5625,
    elevationM: 1372,
    source: 'openstreetmap-nominatim',
    description: 'Panch Prayag near Joshimath — Dhauliganga meets Alaknanda below the Badrinath road.',
  },
  govindghat: {
    key: 'govindghat',
    name: 'Govindghat',
    lng: 79.5619683,
    lat: 30.6192257,
    elevationM: 1829,
    source: 'openstreetmap-nominatim',
  },
  ghangaria: {
    key: 'ghangaria',
    name: 'Ghangaria',
    lng: 79.5938002,
    lat: 30.7014544,
    elevationM: 3048,
    source: 'openstreetmap-nominatim',
  },
  'valley-of-flowers': {
    key: 'valley-of-flowers',
    name: 'Valley of Flowers',
    lng: 79.6177253,
    lat: 30.7430879,
    elevationM: 3350,
    source: 'openstreetmap-nominatim',
  },
  hemkund: {
    key: 'hemkund',
    name: 'Hemkund Sahib',
    lng: 79.608333,
    lat: 30.694444,
    elevationM: 4329,
    source: 'authoritative-reference',
  },
  manali: {
    key: 'manali',
    name: 'Manali',
    lng: 77.1872926,
    lat: 32.2454608,
    elevationM: 2050,
    source: 'openstreetmap-nominatim',
  },
  'hampta-pass': {
    key: 'hampta-pass',
    name: 'Hampta Pass',
    lng: 77.3473609,
    lat: 32.2698793,
    elevationM: 4270,
    source: 'openstreetmap-nominatim',
  },
  pokhara: {
    key: 'pokhara',
    name: 'Pokhara',
    lng: 83.991402,
    lat: 28.209538,
    elevationM: 822,
    source: 'openstreetmap-nominatim',
  },
  'annapurna-base-camp': {
    key: 'annapurna-base-camp',
    name: 'Annapurna Base Camp',
    lng: 83.8778505,
    lat: 28.5307587,
    elevationM: 4130,
    source: 'openstreetmap-nominatim',
  },
  kedarnath: {
    key: 'kedarnath',
    name: 'Kedarnath',
    lng: 79.0669073,
    lat: 30.7338877,
    elevationM: 3583,
    source: 'openstreetmap-nominatim',
  },
  badrinath: {
    key: 'badrinath',
    name: 'Badrinath',
    lng: 79.4930256,
    lat: 30.7423302,
    elevationM: 3133,
    source: 'openstreetmap-nominatim',
  },
  lukla: {
    key: 'lukla',
    name: 'Lukla',
    lng: 86.7288309,
    lat: 27.6865112,
    elevationM: 2860,
    source: 'openstreetmap-nominatim',
  },
  'everest-base-camp': {
    key: 'everest-base-camp',
    name: 'Everest Base Camp',
    lng: 86.8487946,
    lat: 27.9996646,
    elevationM: 5364,
    source: 'openstreetmap-nominatim',
  },
  kathmandu: {
    key: 'kathmandu',
    name: 'Kathmandu',
    lng: 85.3205817,
    lat: 27.708317,
    elevationM: 1400,
    source: 'openstreetmap-nominatim',
  },
  mcleodganj: {
    key: 'mcleodganj',
    name: 'McLeod Ganj',
    lng: 76.326238,
    lat: 32.2352666,
    elevationM: 2082,
    source: 'openstreetmap-nominatim',
  },
  triund: {
    key: 'triund',
    name: 'Triund',
    lng: 76.3545505,
    lat: 32.261444,
    elevationM: 2850,
    source: 'openstreetmap-nominatim',
  },
  chopta: {
    key: 'chopta',
    name: 'Chopta',
    lng: 79.1944,
    lat: 30.4792,
    elevationM: 2680,
    source: 'authoritative-reference',
    description: 'Mini Switzerland of Uttarakhand — meadow campsites and the base for Tungnath and Chandrashila day hikes.',
  },
  chandrashila: {
    key: 'chandrashila',
    name: 'Chandrashila Summit',
    lng: 79.22139,
    lat: 30.48806,
    elevationM: 4130,
    source: 'authoritative-reference',
    description: 'Highest point on the Chopta circuit — panoramic views of Nanda Devi, Trishul, and Chaukhamba from the summit cairn.',
  },
  'sari-village': {
    key: 'sari-village',
    name: 'Sari Village',
    lng: 79.1534,
    lat: 30.5181,
    elevationM: 2000,
    source: 'himalaya-trekker-gps',
  },
  'deoria-tal': {
    key: 'deoria-tal',
    name: 'Deoria Tal',
    lng: 79.12778,
    lat: 30.52222,
    elevationM: 2438,
    source: 'authoritative-reference',
    description: 'Mirror lake reflecting Chaukhamba — short forest trek from Sari village, often done on the final morning.',
  },
  devprayag: {
    key: 'devprayag',
    name: 'Devprayag',
    lng: 78.5983,
    lat: 30.1464,
    elevationM: 618,
    source: 'openstreetmap-nominatim',
    description: 'Sacred confluence of Bhagirathi and Alaknanda — major waypoint on the Rishikesh–Chopta drive.',
  },
  rudraprayag: {
    key: 'rudraprayag',
    name: 'Rudraprayag',
    lng: 78.9819,
    lat: 30.2844,
    elevationM: 895,
    source: 'openstreetmap-nominatim',
    description: 'Junction town where Mandakini meets Alaknanda — fuel and meal stop en route to Ukhimath and Chopta.',
  },
  'srinagar-garhwal': {
    key: 'srinagar-garhwal',
    name: 'Srinagar (Garhwal)',
    lng: 78.7836,
    lat: 30.2247,
    elevationM: 560,
    source: 'authoritative-reference',
    description: 'Major Garhwal town on the Alaknanda highway between Rudraprayag and Devprayag — common meal halt on Joshimath–Rishikesh drives.',
  },
  tharali: {
    key: 'tharali',
    name: 'Tharali',
    lng: 79.538,
    lat: 30.0794,
    elevationM: 2088,
    source: 'authoritative-reference',
    description: 'Tehsil town on the Karnaprayag–Lohajung road — key waypoint on the Brahmatal Day 1 drive.',
  },
  deval: {
    key: 'deval',
    name: 'Deval',
    lng: 79.5109,
    lat: 30.1128,
    elevationM: 1800,
    source: 'authoritative-reference',
    description: 'Last major supply stop before Lohajung — fuel, shops and mobile signal on the Brahmatal approach road.',
  },
  lohajung: {
    key: 'lohajung',
    name: 'Lohajung',
    lng: 79.61906,
    lat: 30.1287685,
    elevationM: 2333,
    source: 'authoritative-reference',
    description:
      'Base village for Brahmatal (~7,600 ft) — guesthouse overnight after the Rishikesh drive; trailhead for Bekaltal and Brahmatal Lake.',
  },
  mundoli: {
    key: 'mundoli',
    name: 'Mandoli (Mundoli)',
    lng: 79.6143579,
    lat: 30.1313208,
    elevationM: 2350,
    source: 'openstreetmap-nominatim',
    description: 'First mountain village on the Lohajung–Bekaltal trail — appears on the left shortly after leaving the base.',
  },
  begum: {
    key: 'begum',
    name: 'Begum',
    lng: 79.59717,
    lat: 30.14515,
    elevationM: 2590,
    source: 'openstreetmap-trail',
    description: 'Rest clearing after the Link-gaad stream bridge — views of Navali and Bagdi Bugyal with Nanda Ghunti on the skyline.',
  },
  gujreni: {
    key: 'gujreni',
    name: 'Gujreni',
    lng: 79.5952,
    lat: 30.15497,
    elevationM: 2800,
    source: 'openstreetmap-trail',
    description: 'Forest clearing and stream area before Bekaltal — popular birdwatching stop; some groups camp here.',
  },
  bekaltal: {
    key: 'bekaltal',
    name: 'Bekaltal',
    lng: 79.5938256,
    lat: 30.1603328,
    elevationM: 2987,
    source: 'openstreetmap-trail',
    description:
      'First high-altitude lake on the Brahmatal route — oak-fringed dystrophic lake with twin-sharing campsite nearby (~9,800 ft).',
  },
  tilandi: {
    key: 'tilandi',
    name: 'Telindi (Tilandi) Top',
    lng: 79.5904304,
    lat: 30.1715934,
    elevationM: 3200,
    source: 'openstreetmap-trail',
    description:
      'Ridge meadow between Bekaltal and Brahmatal — wide Himalayan views on clear days before the approach to the lake.',
  },
  brahmatal: {
    key: 'brahmatal',
    name: 'Brahmatal Lake (Khabekhal)',
    lng: 79.5880158,
    lat: 30.1777927,
    elevationM: 3430,
    source: 'openstreetmap-trail',
    description:
      'High alpine lake that gives the trek its name (also called Khabekhal) — overnight camp; often frozen or snow-bound in peak winter.',
  },
  'chota-jhandidar': {
    key: 'chota-jhandidar',
    name: 'Chota Jhandidar',
    lng: 79.5880808,
    lat: 30.1845166,
    elevationM: 3550,
    source: 'openstreetmap-trail',
    description: 'First exposed ridge step on the Brahmatal summit trail — valleys drop away on both sides.',
  },
  'bada-jhandidar': {
    key: 'bada-jhandidar',
    name: 'Bada Jhandidar',
    lng: 79.588467,
    lat: 30.1912401,
    elevationM: 3650,
    source: 'openstreetmap-trail',
    description: 'Higher ridge step before Brahmatal Top — committing snow and wind section in winter.',
  },
  'brahmatal-summit': {
    key: 'brahmatal-summit',
    name: 'Brahmatal Top',
    lng: 79.5854623,
    lat: 30.1961242,
    elevationM: 3700,
    source: 'openstreetmap-trail',
    description:
      'Summit ridge (~12,150 ft) — panoramas of Mt Trishul, Nanda Ghunti and the wider Garhwal wall when clear.',
  },
  daldum: {
    key: 'daldum',
    name: 'Daldum',
    lng: 79.6015,
    lat: 30.1468,
    elevationM: 2850,
    source: 'project-itinerary',
    description:
      'Forest campsite after the summit descent (~9,350–10,000 ft) — overnight before returning to Lohajung.',
  },
  ukhimath: {
    key: 'ukhimath',
    name: 'Ukhimath',
    lng: 79.0833,
    lat: 30.5167,
    elevationM: 1311,
    source: 'openstreetmap-nominatim',
    description: 'Winter seat of Kedarnath — last substantial town before the climb to Chopta meadows.',
  },
  tungnath: {
    key: 'tungnath',
    name: 'Tungnath',
    lng: 79.216944,
    lat: 30.489722,
    elevationM: 3680,
    source: 'authoritative-reference',
    description: 'World\'s highest Shiva temple — stone steps from Chopta lead through rhododendron forest to this 3,680 m shrine.',
  },
  'har-ki-dun': {
    key: 'har-ki-dun',
    name: 'Har Ki Dun',
    lng: 78.4324156,
    lat: 31.148132,
    elevationM: 3600,
    source: 'openstreetmap-nominatim',
    description:
      'Valley of Gods at ~11,800 ft — amphitheatre of Swargarohini, Hata Peak and Black Peak; Day 4 summit destination before returning to Kalkattiyadhar.',
  },
  'dayara-bugyal': {
    key: 'dayara-bugyal',
    name: 'Dayara Bugyal',
    lng: 78.5496417,
    lat: 30.8299381,
    elevationM: 3658,
    source: 'openstreetmap-nominatim',
  },
  'kuari-pass': {
    key: 'kuari-pass',
    name: 'Kuari Pass',
    lng: 79.5834208,
    lat: 30.455871,
    elevationM: 4264,
    source: 'openstreetmap-nominatim',
  },
  dhak: {
    key: 'dhak',
    name: 'Dhak Village',
    lng: 79.5472,
    lat: 30.5214,
    elevationM: 2300,
    source: 'authoritative-reference',
    description:
      'Trailhead for the Kuari Pass / Curzon Trail — ~12 km / 45 min drive from Joshimath where the trek begins.',
  },
  tugasi: {
    key: 'tugasi',
    name: 'Tugasi',
    lng: 79.5585,
    lat: 30.5055,
    elevationM: 2600,
    source: 'authoritative-reference',
    description:
      'Upper Tugasi hamlet on the Curzon Trail — wheat fields, streams, and first clear views of Mt Dronagiri.',
  },
  'gulling-top': {
    key: 'gulling-top',
    name: 'Gulling Top',
    lng: 79.5688,
    lat: 30.4925,
    elevationM: 2900,
    source: 'authoritative-reference',
    description:
      'Day-2 meadow campsite (~9,264 ft) in oak–rhododendron forest with sunrise views of Dronagiri.',
  },
  tali: {
    key: 'tali',
    name: 'Tali Forest Camp',
    lng: 79.5765,
    lat: 30.4788,
    elevationM: 3350,
    source: 'authoritative-reference',
    description:
      'Day-3 forest campsite (~11,014 ft / 3,350 m) amid oak, rhododendron, and conifers — views of Hathi–Ghoda and Dronagiri.',
  },
  khullara: {
    key: 'khullara',
    name: 'Khullara',
    lng: 79.5808,
    lat: 30.4662,
    elevationM: 3350,
    source: 'authoritative-reference',
    description:
      'High meadow camp (~11,014 ft) at the base of Kuari Pass — Day-4 overnight after the summit push.',
  },
  'nag-tibba': {
    key: 'nag-tibba',
    name: 'Nag Tibba',
    lng: 78.1514926,
    lat: 30.5864629,
    elevationM: 3022,
    source: 'openstreetmap-nominatim',
  },
  pantwari: {
    key: 'pantwari',
    name: 'Pantwari',
    lng: 78.1836,
    lat: 30.4547,
    elevationM: 1350,
    source: 'authoritative-reference',
    description:
      'Base village for Nag Tibba (Tehri Garhwal) — road head after the Dehradun–Mussoorie–Nainbagh drive; trek begins after lunch.',
  },
  'goat-village': {
    key: 'goat-village',
    name: 'Goat Village',
    lng: 78.1685,
    lat: 30.5055,
    elevationM: 1850,
    source: 'authoritative-reference',
    description:
      'Eco-tourism hamlet on the Pantwari–Nag Tibba approach — popular rest stop before the forest crest toward base camp.',
  },
  'nag-tibba-base': {
    key: 'nag-tibba-base',
    name: 'Nag Tibba Base Camp',
    lng: 78.1552,
    lat: 30.5558,
    elevationM: 2500,
    source: 'authoritative-reference',
    description:
      'Overnight forest/ridge camp (~8,200 ft) below the Nag Tibba summit — Day 1 end after the Pantwari trek.',
  },
  'nag-tibba-temple': {
    key: 'nag-tibba-temple',
    name: 'Nag Tibba Temple',
    lng: 78.1524,
    lat: 30.5728,
    elevationM: 2750,
    source: 'authoritative-reference',
    description:
      'Nag Mandir at the foot of the summit cone — Day-2 rest point with Himalayan views before the final steep climb.',
  },
  gaumukh: {
    key: 'gaumukh',
    name: 'Gaumukh',
    lng: 79.0818205,
    lat: 30.9257397,
    elevationM: 4023,
    source: 'openstreetmap-nominatim',
  },
  gangotri: {
    key: 'gangotri',
    name: 'Gangotri',
    lng: 78.9411466,
    lat: 30.9944345,
    elevationM: 3415,
    source: 'openstreetmap-nominatim',
  },
  'bali-pass': {
    key: 'bali-pass',
    name: 'Bali Pass',
    lng: 78.4628898,
    lat: 30.999972,
    elevationM: 4900,
    source: 'openstreetmap-nominatim',
  },
  'rupin-pass': {
    key: 'rupin-pass',
    name: 'Rupin Pass',
    lng: 78.1544996,
    lat: 31.354091,
    elevationM: 4650,
    source: 'openstreetmap-nominatim',
  },
  kasol: {
    key: 'kasol',
    name: 'Kasol',
    lng: 77.3166036,
    lat: 32.0104317,
    elevationM: 1640,
    source: 'openstreetmap-nominatim',
  },
  'beas-kund': {
    key: 'beas-kund',
    name: 'Beas Kund',
    lng: 77.0855604,
    lat: 32.3665397,
    elevationM: 3700,
    source: 'openstreetmap-nominatim',
  },
  'bhrigu-lake': {
    key: 'bhrigu-lake',
    name: 'Bhrigu Lake',
    lng: 77.2424985,
    lat: 32.2932605,
    elevationM: 4300,
    source: 'openstreetmap-nominatim',
  },
  'yulla-kanda': {
    key: 'yulla-kanda',
    name: 'Yulla Kanda',
    lng: 78.1407753,
    lat: 31.5905581,
    elevationM: 3900,
    source: 'openstreetmap-nominatim',
  },
  'buran-ghati': {
    key: 'buran-ghati',
    name: 'Buran Ghati',
    lng: 78.1459193,
    lat: 31.3877931,
    elevationM: 4575,
    source: 'openstreetmap-nominatim',
  },
  chitwan: {
    key: 'chitwan',
    name: 'Chitwan National Park',
    lng: 84.4382935,
    lat: 27.5168214,
    elevationM: 150,
    source: 'openstreetmap-nominatim',
  },
};

export function getLocation(key: string): GeoLocation | undefined {
  return LOCATIONS[key];
}

/** Fuzzy match itinerary labels to verified location keys. */
export function matchLocationKey(label: string): string | null {
  const norm = label.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();

  const rules: [RegExp, string][] = [
    [/dehradun/, 'dehradun-railway'],
    [/sankri/, 'sankri'],
    [/taluka/, 'taluka'],
    [/pauni|puani.?gara/, 'pauni-garaat'],
    [/seema/, 'seema'],
    [/osla/, 'osla'],
    [/kalkatti|kalkati.?dhar/, 'kalkattiyadhar'],
    [/juda/, 'juda-ka-talab'],
    [/kedarkantha base|base camp/, 'kedarkantha-base'],
    [/kedarkantha|summit day|summit/, 'kedarkantha-summit'],
    [/hargaon/, 'hargaon'],
    [/rishikesh/, 'rishikesh'],
    [/govindghat/, 'govindghat'],
    [/ghangaria/, 'ghangaria'],
    [/valley of flowers/, 'valley-of-flowers'],
    [/hemkund/, 'hemkund'],
    [/manali/, 'manali'],
    [/hampta/, 'hampta-pass'],
    [/pokhara/, 'pokhara'],
    [/annapurna base|abc/, 'annapurna-base-camp'],
    [/kedarnath/, 'kedarnath'],
    [/badrinath/, 'badrinath'],
    [/lukla/, 'lukla'],
    [/everest base|ebc/, 'everest-base-camp'],
    [/kathmandu/, 'kathmandu'],
    [/mcleod|triund/, 'triund'],
    [/chopta/, 'chopta'],
    [/tungnath/, 'tungnath'],
    [/chandrashila/, 'chandrashila'],
    [/deoria|deoriatal/, 'deoria-tal'],
    [/sari village|sari/, 'sari-village'],
    [/har ki dun/, 'har-ki-dun'],
    [/dayara/, 'dayara-bugyal'],
    [/joshimath/, 'joshimath'],
    [/dhak/, 'dhak'],
    [/tugasi|tugasi village/, 'tugasi'],
    [/gulling/, 'gulling-top'],
    [/tali|talli forest|talli/, 'tali'],
    [/khullara/, 'khullara'],
    [/devprayag/, 'devprayag'],
    [/rudraprayag/, 'rudraprayag'],
    [/srinagar \(garhwal\)|srinagar garhwal/, 'srinagar-garhwal'],
    [/karnaprayag|karanprayag/, 'karnaprayag'],
    [/nandaprayag/, 'nandaprayag'],
    [/vishnuprayag/, 'vishnuprayag'],
    [/tharali/, 'tharali'],
    [/\bdeval\b/, 'deval'],
    [/lohajung|loha jung/, 'lohajung'],
    [/mandoli|mundoli/, 'mundoli'],
    [/begum/, 'begum'],
    [/gujreni|gujareni/, 'gujreni'],
    [/bekaltal|bekal tal/, 'bekaltal'],
    [/tilandi|telindi|telandi|tilangi/, 'tilandi'],
    [/chota.?jhandi/, 'chota-jhandidar'],
    [/bada.?jhandi/, 'bada-jhandidar'],
    [/daldum|daldam/, 'daldum'],
    [/brahmatal summit|brahmatal top|brahmatal ridge|jhandi top/, 'brahmatal-summit'],
    [/brahmatal|bhramatal|bharamtal|khabekhal/, 'brahmatal'],
    [/kuari/, 'kuari-pass'],
    [/nag tibba temple|nag mandir/, 'nag-tibba-temple'],
    [/nag tibba base|nag.?tibba camp/, 'nag-tibba-base'],
    [/nag tibba/, 'nag-tibba'],
    [/pantwari|panthwari/, 'pantwari'],
    [/goat village/, 'goat-village'],
    [/kempty/, 'kempty-falls'],
    [/mussoorie/, 'mussoorie'],
    [/nainbag/, 'nainbag'],
    [/gaumukh|tapovan/, 'gaumukh'],
    [/gangotri/, 'gangotri'],
    [/bali pass/, 'bali-pass'],
    [/rupin/, 'rupin-pass'],
    [/kasol|sar pass/, 'kasol'],
    [/beas kund/, 'beas-kund'],
    [/bhrigu/, 'bhrigu-lake'],
    [/yulla/, 'yulla-kanda'],
    [/buran/, 'buran-ghati'],
    [/chitwan/, 'chitwan'],
  ];

  for (const [pattern, key] of rules) {
    if (pattern.test(norm)) return key;
  }

  for (const loc of Object.values(LOCATIONS)) {
    if (norm.includes(loc.name.toLowerCase())) return loc.key;
  }

  return null;
}
