import type { GeoLocation } from './types';

/**
 * Verified geographic coordinates used by trek route maps.
 * Sources:
 * - openstreetmap-nominatim: OpenStreetMap Nominatim API (ODbL), queried Aug 2026
 * - himalaya-trekker-gps: Published trek-operator GPS for Kedarkantha summit
 * - authoritative-reference: Commonly cited coordinates for named peaks/temples
 */
export const LOCATIONS: Record<string, GeoLocation> = {
  'dehradun-railway': {
    key: 'dehradun-railway',
    name: 'Dehradun Railway Station',
    lng: 78.0335416,
    lat: 30.3125021,
    elevationM: 640,
    source: 'openstreetmap-nominatim',
  },
  mussoorie: {
    key: 'mussoorie',
    name: 'Mussoorie',
    lng: 78.0782906,
    lat: 30.4569012,
    elevationM: 2005,
    source: 'openstreetmap-nominatim',
  },
  purola: {
    key: 'purola',
    name: 'Purola',
    lng: 78.414,
    lat: 30.748,
    elevationM: 1524,
    source: 'authoritative-reference',
  },
  sankri: {
    key: 'sankri',
    name: 'Sankri',
    lng: 78.1841131,
    lat: 31.078024,
    elevationM: 1950,
    source: 'openstreetmap-nominatim',
  },
  'juda-ka-talab': {
    key: 'juda-ka-talab',
    name: 'Juda Ka Talab',
    lng: 78.1843029,
    lat: 31.0524927,
    elevationM: 2773,
    source: 'openstreetmap-nominatim',
  },
  'kedarkantha-base': {
    key: 'kedarkantha-base',
    name: 'Kedarkantha Base Camp',
    lng: 78.1802171,
    lat: 31.0586527,
    elevationM: 3200,
    source: 'openstreetmap-nominatim',
  },
  'kedarkantha-summit': {
    key: 'kedarkantha-summit',
    name: 'Kedarkantha Summit',
    lng: 78.17185,
    lat: 31.02257,
    elevationM: 3810,
    source: 'himalaya-trekker-gps',
  },
  hargaon: {
    key: 'hargaon',
    name: 'Hargaon Thach',
    lng: 78.1800651,
    lat: 31.0581682,
    elevationM: 2645,
    source: 'openstreetmap-nominatim',
  },
  rishikesh: {
    key: 'rishikesh',
    name: 'Rishikesh',
    lng: 78.2916193,
    lat: 30.1086537,
    elevationM: 372,
    source: 'openstreetmap-nominatim',
  },
  joshimath: {
    key: 'joshimath',
    name: 'Joshimath',
    lng: 79.5612607,
    lat: 30.5555752,
    elevationM: 1890,
    source: 'openstreetmap-nominatim',
  },
  govindghat: {
    key: 'govindghat',
    name: 'Govindghat',
    lng: 79.5619683,
    lat: 30.6192257,
    elevationM: 1829,
    source: 'openstreetmap-nominatim',
  },
  ghangaria: {
    key: 'ghangaria',
    name: 'Ghangaria',
    lng: 79.5938002,
    lat: 30.7014544,
    elevationM: 3048,
    source: 'openstreetmap-nominatim',
  },
  'valley-of-flowers': {
    key: 'valley-of-flowers',
    name: 'Valley of Flowers',
    lng: 79.6177253,
    lat: 30.7430879,
    elevationM: 3350,
    source: 'openstreetmap-nominatim',
  },
  hemkund: {
    key: 'hemkund',
    name: 'Hemkund Sahib',
    lng: 79.608333,
    lat: 30.694444,
    elevationM: 4329,
    source: 'authoritative-reference',
  },
  manali: {
    key: 'manali',
    name: 'Manali',
    lng: 77.1872926,
    lat: 32.2454608,
    elevationM: 2050,
    source: 'openstreetmap-nominatim',
  },
  'hampta-pass': {
    key: 'hampta-pass',
    name: 'Hampta Pass',
    lng: 77.3473609,
    lat: 32.2698793,
    elevationM: 4270,
    source: 'openstreetmap-nominatim',
  },
  pokhara: {
    key: 'pokhara',
    name: 'Pokhara',
    lng: 83.991402,
    lat: 28.209538,
    elevationM: 822,
    source: 'openstreetmap-nominatim',
  },
  'annapurna-base-camp': {
    key: 'annapurna-base-camp',
    name: 'Annapurna Base Camp',
    lng: 83.8778505,
    lat: 28.5307587,
    elevationM: 4130,
    source: 'openstreetmap-nominatim',
  },
  kedarnath: {
    key: 'kedarnath',
    name: 'Kedarnath',
    lng: 79.0669073,
    lat: 30.7338877,
    elevationM: 3583,
    source: 'openstreetmap-nominatim',
  },
  badrinath: {
    key: 'badrinath',
    name: 'Badrinath',
    lng: 79.4930256,
    lat: 30.7423302,
    elevationM: 3133,
    source: 'openstreetmap-nominatim',
  },
  lukla: {
    key: 'lukla',
    name: 'Lukla',
    lng: 86.7288309,
    lat: 27.6865112,
    elevationM: 2860,
    source: 'openstreetmap-nominatim',
  },
  'everest-base-camp': {
    key: 'everest-base-camp',
    name: 'Everest Base Camp',
    lng: 86.8487946,
    lat: 27.9996646,
    elevationM: 5364,
    source: 'openstreetmap-nominatim',
  },
  kathmandu: {
    key: 'kathmandu',
    name: 'Kathmandu',
    lng: 85.3205817,
    lat: 27.708317,
    elevationM: 1400,
    source: 'openstreetmap-nominatim',
  },
  mcleodganj: {
    key: 'mcleodganj',
    name: 'McLeod Ganj',
    lng: 76.326238,
    lat: 32.2352666,
    elevationM: 2082,
    source: 'openstreetmap-nominatim',
  },
  triund: {
    key: 'triund',
    name: 'Triund',
    lng: 76.3545505,
    lat: 32.261444,
    elevationM: 2850,
    source: 'openstreetmap-nominatim',
  },
  chopta: {
    key: 'chopta',
    name: 'Chopta',
    lng: 79.367685,
    lat: 30.1801851,
    elevationM: 2680,
    source: 'openstreetmap-nominatim',
  },
  tungnath: {
    key: 'tungnath',
    name: 'Tungnath',
    lng: 79.216944,
    lat: 30.489722,
    elevationM: 3680,
    source: 'authoritative-reference',
  },
  'har-ki-dun': {
    key: 'har-ki-dun',
    name: 'Har Ki Dun',
    lng: 78.4324156,
    lat: 31.148132,
    elevationM: 3506,
    source: 'openstreetmap-nominatim',
  },
  'dayara-bugyal': {
    key: 'dayara-bugyal',
    name: 'Dayara Bugyal',
    lng: 78.5496417,
    lat: 30.8299381,
    elevationM: 3658,
    source: 'openstreetmap-nominatim',
  },
  'kuari-pass': {
    key: 'kuari-pass',
    name: 'Kuari Pass',
    lng: 79.5834208,
    lat: 30.455871,
    elevationM: 4264,
    source: 'openstreetmap-nominatim',
  },
  'nag-tibba': {
    key: 'nag-tibba',
    name: 'Nag Tibba',
    lng: 78.1514926,
    lat: 30.5864629,
    elevationM: 3022,
    source: 'openstreetmap-nominatim',
  },
  gaumukh: {
    key: 'gaumukh',
    name: 'Gaumukh',
    lng: 79.0818205,
    lat: 30.9257397,
    elevationM: 4023,
    source: 'openstreetmap-nominatim',
  },
  gangotri: {
    key: 'gangotri',
    name: 'Gangotri',
    lng: 78.9411466,
    lat: 30.9944345,
    elevationM: 3415,
    source: 'openstreetmap-nominatim',
  },
  'bali-pass': {
    key: 'bali-pass',
    name: 'Bali Pass',
    lng: 78.4628898,
    lat: 30.999972,
    elevationM: 4900,
    source: 'openstreetmap-nominatim',
  },
  'rupin-pass': {
    key: 'rupin-pass',
    name: 'Rupin Pass',
    lng: 78.1544996,
    lat: 31.354091,
    elevationM: 4650,
    source: 'openstreetmap-nominatim',
  },
  kasol: {
    key: 'kasol',
    name: 'Kasol',
    lng: 77.3166036,
    lat: 32.0104317,
    elevationM: 1640,
    source: 'openstreetmap-nominatim',
  },
  'beas-kund': {
    key: 'beas-kund',
    name: 'Beas Kund',
    lng: 77.0855604,
    lat: 32.3665397,
    elevationM: 3700,
    source: 'openstreetmap-nominatim',
  },
  'bhrigu-lake': {
    key: 'bhrigu-lake',
    name: 'Bhrigu Lake',
    lng: 77.2424985,
    lat: 32.2932605,
    elevationM: 4300,
    source: 'openstreetmap-nominatim',
  },
  'yulla-kanda': {
    key: 'yulla-kanda',
    name: 'Yulla Kanda',
    lng: 78.1407753,
    lat: 31.5905581,
    elevationM: 3900,
    source: 'openstreetmap-nominatim',
  },
  'buran-ghati': {
    key: 'buran-ghati',
    name: 'Buran Ghati',
    lng: 78.1459193,
    lat: 31.3877931,
    elevationM: 4575,
    source: 'openstreetmap-nominatim',
  },
  chitwan: {
    key: 'chitwan',
    name: 'Chitwan National Park',
    lng: 84.4382935,
    lat: 27.5168214,
    elevationM: 150,
    source: 'openstreetmap-nominatim',
  },
};

export function getLocation(key: string): GeoLocation | undefined {
  return LOCATIONS[key];
}

/** Fuzzy match itinerary labels to verified location keys. */
export function matchLocationKey(label: string): string | null {
  const norm = label.toLowerCase().replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();

  const rules: [RegExp, string][] = [
    [/dehradun/, 'dehradun-railway'],
    [/sankri/, 'sankri'],
    [/juda/, 'juda-ka-talab'],
    [/kedarkantha base|base camp/, 'kedarkantha-base'],
    [/kedarkantha|summit day|summit/, 'kedarkantha-summit'],
    [/hargaon/, 'hargaon'],
    [/rishikesh/, 'rishikesh'],
    [/govindghat/, 'govindghat'],
    [/ghangaria/, 'ghangaria'],
    [/valley of flowers/, 'valley-of-flowers'],
    [/hemkund/, 'hemkund'],
    [/manali/, 'manali'],
    [/hampta/, 'hampta-pass'],
    [/pokhara/, 'pokhara'],
    [/annapurna base|abc/, 'annapurna-base-camp'],
    [/kedarnath/, 'kedarnath'],
    [/badrinath/, 'badrinath'],
    [/lukla/, 'lukla'],
    [/everest base|ebc/, 'everest-base-camp'],
    [/kathmandu/, 'kathmandu'],
    [/mcleod|triund/, 'triund'],
    [/chopta/, 'chopta'],
    [/tungnath|chandrashila/, 'tungnath'],
    [/har ki dun/, 'har-ki-dun'],
    [/dayara/, 'dayara-bugyal'],
    [/kuari/, 'kuari-pass'],
    [/nag tibba/, 'nag-tibba'],
    [/gaumukh|tapovan/, 'gaumukh'],
    [/gangotri/, 'gangotri'],
    [/bali pass/, 'bali-pass'],
    [/rupin/, 'rupin-pass'],
    [/kasol|sar pass/, 'kasol'],
    [/beas kund/, 'beas-kund'],
    [/bhrigu/, 'bhrigu-lake'],
    [/yulla/, 'yulla-kanda'],
    [/buran/, 'buran-ghati'],
    [/chitwan/, 'chitwan'],
  ];

  for (const [pattern, key] of rules) {
    if (pattern.test(norm)) return key;
  }

  for (const loc of Object.values(LOCATIONS)) {
    if (norm.includes(loc.name.toLowerCase())) return loc.key;
  }

  return null;
}
