import type { TrekRouteDefinition } from './types';

/** Explicit trek routes — every location key must exist in locations.ts. */
export const TREK_ROUTES: Record<string, TrekRouteDefinition> = {
  kedarkantha: {
    trekId: 'kedarkantha',
    driveVia: ['mussoorie', 'nainbag', 'naugaon', 'purola', 'mori', 'netwar'],
    caption:
      '5-day Kedarkantha itinerary — Day 1 drive via Naugaon, Purola, Mori and Netwar to Sankri; Days 2–4 trek to summit and Hargaon; Day 5 return to Dehradun.',
    waypoints: [
      { day: 1, locationKey: 'dehradun-railway', kind: 'start', activity: 'drive', markerRole: 'primary' },
      { day: 2, locationKey: 'juda-ka-talab', kind: 'water', activity: 'trek', markerRole: 'primary' },
      { day: 3, locationKey: 'kedarkantha-base', kind: 'base-camp', activity: 'trek', markerRole: 'primary' },
      { day: 4, locationKey: 'kedarkantha-summit', kind: 'summit', activity: 'summit', markerRole: 'primary' },
      { day: 5, locationKey: 'dehradun-railway', kind: 'end', activity: 'drive', markerRole: 'primary' },
    ],
    trailStops: [
      { locationKey: 'sankri', kind: 'village', label: 'Sankri', itineraryDay: 2 },
      { locationKey: 'juda-ka-talab', kind: 'water', label: 'Juda Ka Talab', itineraryDay: 2 },
      { locationKey: 'kedarkantha-base', kind: 'base-camp', label: 'Base Camp', itineraryDay: 3 },
      { locationKey: 'kedarkantha-summit', kind: 'summit', label: 'Summit', itineraryDay: 4, pinExact: true },
      { locationKey: 'hargaon', kind: 'camp', label: 'Hargaon Thach', itineraryDay: 4 },
    ],
    routeSegments: [
      {
        id: 'day1-drive',
        geometryKind: 'driving-network',
        trackKey: 'kedarkantha-day1-drive',
        driveFrom: 'dehradun-railway',
        driveTo: 'sankri',
        driveVia: ['mussoorie', 'nainbag', 'naugaon', 'purola', 'mori', 'netwar'],
        dayStart: 1,
        dayEnd: 1,
      },
      {
        id: 'trek-full',
        geometryKind: 'gps-track',
        trackKey: 'kedarkantha-trek-full',
        dayStart: 2,
        dayEnd: 5,
      },
      {
        id: 'day5-drive',
        geometryKind: 'driving-network',
        trackKey: 'kedarkantha-day5-drive',
        driveFrom: 'sankri',
        driveTo: 'dehradun-railway',
        driveVia: ['netwar', 'mori', 'purola', 'naugaon', 'nainbag', 'mussoorie'],
        dayStart: 5,
        dayEnd: 5,
      },
    ],
  },
  'valley-of-flowers': {
    trekId: 'valley-of-flowers',
    waypoints: [
      { day: 1, locationKey: 'rishikesh', kind: 'start', activity: 'drive' },
      { day: 1, locationKey: 'govindghat', kind: 'village', activity: 'drive' },
      { day: 2, locationKey: 'ghangaria', kind: 'camp', activity: 'trek' },
      { day: 3, locationKey: 'valley-of-flowers', kind: 'viewpoint', activity: 'trek' },
      { day: 4, locationKey: 'hemkund', kind: 'temple', activity: 'trek' },
      { day: 5, locationKey: 'govindghat', kind: 'village', activity: 'trek' },
      { day: 5, locationKey: 'rishikesh', kind: 'end', activity: 'drive' },
    ],
  },
  'hampta-pass': {
    trekId: 'hampta-pass',
    waypoints: [
      { day: 1, locationKey: 'manali', kind: 'start', activity: 'drive' },
      { day: 3, locationKey: 'hampta-pass', kind: 'pass', activity: 'summit' },
      { day: 5, locationKey: 'manali', kind: 'end', activity: 'drive' },
    ],
  },
  'annapurna-base-camp': {
    trekId: 'annapurna-base-camp',
    waypoints: [
      { day: 1, locationKey: 'pokhara', kind: 'start', activity: 'drive' },
      { day: 6, locationKey: 'annapurna-base-camp', kind: 'base-camp', activity: 'summit' },
      { day: 8, locationKey: 'pokhara', kind: 'end', activity: 'drive' },
    ],
  },
  'kedarnath-yatra': {
    trekId: 'kedarnath-yatra',
    waypoints: [
      { day: 1, locationKey: 'rishikesh', kind: 'start', activity: 'drive' },
      { day: 2, locationKey: 'kedarnath', kind: 'temple', activity: 'trek' },
      { day: 4, locationKey: 'rishikesh', kind: 'end', activity: 'drive' },
    ],
  },
  'everest-base-camp': {
    trekId: 'everest-base-camp',
    waypoints: [
      { day: 1, locationKey: 'kathmandu', kind: 'start', activity: 'drive' },
      { day: 1, locationKey: 'lukla', kind: 'village', activity: 'drive' },
      { day: 8, locationKey: 'everest-base-camp', kind: 'base-camp', activity: 'summit' },
      { day: 12, locationKey: 'lukla', kind: 'village', activity: 'trek' },
      { day: 13, locationKey: 'kathmandu', kind: 'end', activity: 'drive' },
    ],
  },
  'mcleodganj-trek': {
    trekId: 'mcleodganj-trek',
    waypoints: [
      { day: 1, locationKey: 'mcleodganj', kind: 'start', activity: 'rest' },
      { day: 2, locationKey: 'triund', kind: 'camp', activity: 'trek' },
      { day: 3, locationKey: 'mcleodganj', kind: 'end', activity: 'trek' },
    ],
  },
  'chopta-tungnath': {
    trekId: 'chopta-tungnath',
    driveVia: ['devprayag', 'rudraprayag', 'ukhimath'],
    caption:
      '3-day Chopta Tungnath itinerary — Day 1 drive Rishikesh → Chopta · Day 2 trek to Tungnath, Chandrashila & Sari · Day 3 Deoria Tal trek and return drive to Rishikesh.',
    waypoints: [
      { day: 1, locationKey: 'rishikesh', kind: 'start', activity: 'drive', markerRole: 'primary' },
      { day: 2, locationKey: 'chandrashila', kind: 'summit', activity: 'summit', markerRole: 'primary' },
      { day: 3, locationKey: 'rishikesh', kind: 'end', activity: 'drive', markerRole: 'primary' },
    ],
    trailStops: [
      { locationKey: 'chopta', kind: 'camp', label: 'Chopta Camp', itineraryDay: 1 },
      { locationKey: 'tungnath', kind: 'temple', label: 'Tungnath Temple', itineraryDay: 2 },
      { locationKey: 'chandrashila', kind: 'summit', label: 'Chandrashila', itineraryDay: 2, pinExact: true },
      { locationKey: 'sari-village', kind: 'village', label: 'Sari Village', itineraryDay: 2 },
      { locationKey: 'deoria-tal', kind: 'water', label: 'Deoria Tal', itineraryDay: 3 },
    ],
    routeSegments: [
      {
        id: 'day1-drive',
        geometryKind: 'driving-network',
        driveFrom: 'rishikesh',
        driveTo: 'chopta',
        driveVia: ['devprayag', 'rudraprayag', 'ukhimath'],
        dayStart: 1,
        dayEnd: 1,
      },
      {
        id: 'day2-trek',
        geometryKind: 'gps-track',
        trackKey: 'chopta-day2-trek',
        dayStart: 2,
        dayEnd: 2,
      },
      {
        id: 'day3-trek',
        geometryKind: 'gps-track',
        trackKey: 'chopta-day3-trek',
        dayStart: 3,
        dayEnd: 3,
      },
      {
        id: 'day3-drive',
        geometryKind: 'driving-network',
        driveFrom: 'sari-village',
        driveTo: 'rishikesh',
        driveVia: ['ukhimath', 'rudraprayag', 'devprayag'],
        dayStart: 3,
        dayEnd: 3,
      },
    ],
  },
  'badrinath-yatra': {
    trekId: 'badrinath-yatra',
    waypoints: [
      { day: 1, locationKey: 'rishikesh', kind: 'start', activity: 'drive' },
      { day: 2, locationKey: 'badrinath', kind: 'temple', activity: 'drive' },
      { day: 4, locationKey: 'rishikesh', kind: 'end', activity: 'drive' },
    ],
  },
  'dayara-bugyal': {
    trekId: 'dayara-bugyal',
    waypoints: [
      { day: 1, locationKey: 'rishikesh', kind: 'start', activity: 'drive' },
      { day: 3, locationKey: 'dayara-bugyal', kind: 'viewpoint', activity: 'trek' },
      { day: 5, locationKey: 'rishikesh', kind: 'end', activity: 'drive' },
    ],
  },
  'har-ki-dun': {
    trekId: 'har-ki-dun',
    waypoints: [
      { day: 1, locationKey: 'dehradun-railway', kind: 'start', activity: 'drive' },
      { day: 1, locationKey: 'sankri', kind: 'village', activity: 'drive' },
      { day: 2, locationKey: 'juda-ka-talab', kind: 'water', activity: 'trek' },
      { day: 3, locationKey: 'har-ki-dun', kind: 'viewpoint', activity: 'trek' },
      { day: 5, locationKey: 'sankri', kind: 'village', activity: 'trek' },
      { day: 6, locationKey: 'dehradun-railway', kind: 'end', activity: 'drive' },
    ],
  },
  'kuari-pass': {
    trekId: 'kuari-pass',
    driveVia: ['devprayag', 'rudraprayag', 'karnaprayag', 'nandaprayag', 'vishnuprayag'],
    caption:
      '6-day Kuari Pass (Curzon Trail) — Day 1 Rishikesh → Joshimath via Panch Prayag; Day 2 Joshimath → Dhak → Gulling Top; Day 3 Gulling Top → Tali; Day 4 Khullara → Kuari Pass → Khullara; Day 5 Khullara → Tugasi → Joshimath; Day 6 Joshimath → Rishikesh → Dehradun.',
    waypoints: [
      { day: 1, locationKey: 'rishikesh', kind: 'start', activity: 'drive', markerRole: 'primary' },
      { day: 1, locationKey: 'devprayag', kind: 'viewpoint', activity: 'drive', markerRole: 'secondary' },
      { day: 1, locationKey: 'rudraprayag', kind: 'viewpoint', activity: 'drive', markerRole: 'secondary' },
      { day: 1, locationKey: 'karnaprayag', kind: 'viewpoint', activity: 'drive', markerRole: 'secondary' },
      { day: 1, locationKey: 'nandaprayag', kind: 'viewpoint', activity: 'drive', markerRole: 'secondary' },
      { day: 1, locationKey: 'vishnuprayag', kind: 'viewpoint', activity: 'drive', markerRole: 'secondary' },
      { day: 1, locationKey: 'joshimath', kind: 'village', activity: 'drive', markerRole: 'secondary' },
      { day: 2, locationKey: 'joshimath', kind: 'village', activity: 'drive', markerRole: 'secondary' },
      { day: 2, locationKey: 'dhak', kind: 'village', activity: 'trek', markerRole: 'secondary' },
      { day: 2, locationKey: 'tugasi', kind: 'village', activity: 'trek', markerRole: 'secondary' },
      { day: 2, locationKey: 'gulling-top', kind: 'camp', activity: 'trek', markerRole: 'primary' },
      { day: 3, locationKey: 'gulling-top', kind: 'camp', activity: 'trek', markerRole: 'secondary' },
      { day: 3, locationKey: 'tali', kind: 'camp', activity: 'trek', markerRole: 'primary' },
      { day: 4, locationKey: 'khullara', kind: 'camp', activity: 'trek', markerRole: 'secondary' },
      { day: 4, locationKey: 'kuari-pass', kind: 'pass', activity: 'summit', markerRole: 'primary' },
      { day: 5, locationKey: 'khullara', kind: 'camp', activity: 'trek', markerRole: 'secondary' },
      { day: 5, locationKey: 'tugasi', kind: 'village', activity: 'trek', markerRole: 'secondary' },
      { day: 5, locationKey: 'joshimath', kind: 'village', activity: 'drive', markerRole: 'primary' },
      { day: 6, locationKey: 'joshimath', kind: 'village', activity: 'drive', markerRole: 'secondary' },
      { day: 6, locationKey: 'nandaprayag', kind: 'viewpoint', activity: 'drive', markerRole: 'secondary' },
      { day: 6, locationKey: 'karnaprayag', kind: 'viewpoint', activity: 'drive', markerRole: 'secondary' },
      { day: 6, locationKey: 'rudraprayag', kind: 'viewpoint', activity: 'drive', markerRole: 'secondary' },
      { day: 6, locationKey: 'srinagar-garhwal', kind: 'village', activity: 'drive', markerRole: 'secondary' },
      { day: 6, locationKey: 'devprayag', kind: 'viewpoint', activity: 'drive', markerRole: 'secondary' },
      { day: 6, locationKey: 'rishikesh', kind: 'village', activity: 'drive', markerRole: 'secondary' },
      { day: 6, locationKey: 'dehradun-railway', kind: 'end', activity: 'drive', markerRole: 'primary' },
    ],
    trailStops: [
      { locationKey: 'joshimath', kind: 'village', label: 'Joshimath overnight', itineraryDay: 1 },
      { locationKey: 'dhak', kind: 'village', label: 'Dhak trailhead', itineraryDay: 2 },
      { locationKey: 'tugasi', kind: 'village', label: 'Tugasi', itineraryDay: 2 },
      { locationKey: 'gulling-top', kind: 'camp', label: 'Gulling Top camp', itineraryDay: 2 },
      { locationKey: 'tali', kind: 'camp', label: 'Tali Forest Camp', itineraryDay: 3 },
      { locationKey: 'khullara', kind: 'camp', label: 'Khullara camp', itineraryDay: 4 },
      { locationKey: 'kuari-pass', kind: 'pass', label: 'Kuari Pass summit', itineraryDay: 4, pinExact: true },
      { locationKey: 'tugasi', kind: 'village', label: 'Tugasi road head', itineraryDay: 5 },
      { locationKey: 'joshimath', kind: 'village', label: 'Joshimath hotel', itineraryDay: 5 },
      { locationKey: 'rishikesh', kind: 'village', label: 'Rishikesh drop zone', itineraryDay: 6 },
      { locationKey: 'dehradun-railway', kind: 'end', label: 'Dehradun Railway Station', itineraryDay: 6 },
    ],
    routeSegments: [
      {
        id: 'day1-drive',
        geometryKind: 'driving-network',
        trackKey: 'kuari-pass-day1-drive',
        driveFrom: 'rishikesh',
        driveTo: 'joshimath',
        driveVia: ['devprayag', 'rudraprayag', 'karnaprayag', 'nandaprayag', 'vishnuprayag'],
        dayStart: 1,
        dayEnd: 1,
      },
      {
        id: 'day2-drive',
        geometryKind: 'driving-network',
        trackKey: 'kuari-pass-day2-drive',
        driveFrom: 'joshimath',
        driveTo: 'dhak',
        driveVia: [],
        dayStart: 2,
        dayEnd: 2,
      },
      {
        id: 'day2-trek',
        geometryKind: 'gps-track',
        trackKey: 'kuari-pass-day2-trek',
        driveFrom: 'dhak',
        driveTo: 'gulling-top',
        driveVia: [],
        dayStart: 2,
        dayEnd: 2,
      },
      {
        id: 'day3-trek',
        geometryKind: 'gps-track',
        trackKey: 'kuari-pass-day3-trek',
        driveFrom: 'gulling-top',
        driveTo: 'tali',
        driveVia: [],
        dayStart: 3,
        dayEnd: 3,
      },
      {
        id: 'day4-summit',
        geometryKind: 'gps-track',
        trackKey: 'kuari-pass-day4-summit',
        driveFrom: 'khullara',
        driveTo: 'kuari-pass',
        driveVia: [],
        dayStart: 4,
        dayEnd: 4,
      },
      {
        id: 'day5-trek',
        geometryKind: 'gps-track',
        trackKey: 'kuari-pass-day5-trek',
        driveFrom: 'khullara',
        driveTo: 'tugasi',
        driveVia: [],
        dayStart: 5,
        dayEnd: 5,
      },
      {
        id: 'day5-drive',
        geometryKind: 'driving-network',
        trackKey: 'kuari-pass-day5-drive',
        driveFrom: 'tugasi',
        driveTo: 'joshimath',
        driveVia: [],
        dayStart: 5,
        dayEnd: 5,
      },
      {
        id: 'day6-drive',
        geometryKind: 'driving-network',
        trackKey: 'kuari-pass-day6-drive',
        driveFrom: 'joshimath',
        driveTo: 'dehradun-railway',
        driveVia: [
          'nandaprayag',
          'karnaprayag',
          'rudraprayag',
          'srinagar-garhwal',
          'devprayag',
          'rishikesh',
        ],
        dayStart: 6,
        dayEnd: 6,
      },
    ],
  },
  'nag-tibba': {
    trekId: 'nag-tibba',
    waypoints: [
      { day: 1, locationKey: 'dehradun-railway', kind: 'start', activity: 'drive' },
      { day: 2, locationKey: 'nag-tibba', kind: 'summit', activity: 'summit' },
      { day: 3, locationKey: 'dehradun-railway', kind: 'end', activity: 'drive' },
    ],
  },
  'gaumukh-tapovan': {
    trekId: 'gaumukh-tapovan',
    waypoints: [
      { day: 1, locationKey: 'rishikesh', kind: 'start', activity: 'drive' },
      { day: 1, locationKey: 'gangotri', kind: 'temple', activity: 'drive' },
      { day: 4, locationKey: 'gaumukh', kind: 'viewpoint', activity: 'trek' },
      { day: 6, locationKey: 'rishikesh', kind: 'end', activity: 'drive' },
    ],
  },
  'bali-pass': {
    trekId: 'bali-pass',
    waypoints: [
      { day: 1, locationKey: 'dehradun-railway', kind: 'start', activity: 'drive' },
      { day: 4, locationKey: 'bali-pass', kind: 'pass', activity: 'summit' },
      { day: 6, locationKey: 'dehradun-railway', kind: 'end', activity: 'drive' },
    ],
  },
  'rupin-pass': {
    trekId: 'rupin-pass',
    waypoints: [
      { day: 1, locationKey: 'dehradun-railway', kind: 'start', activity: 'drive' },
      { day: 5, locationKey: 'rupin-pass', kind: 'pass', activity: 'summit' },
      { day: 7, locationKey: 'dehradun-railway', kind: 'end', activity: 'drive' },
    ],
  },
  'sar-pass': {
    trekId: 'sar-pass',
    waypoints: [
      { day: 1, locationKey: 'kasol', kind: 'start', activity: 'rest' },
      { day: 3, locationKey: 'kasol', kind: 'end', activity: 'trek' },
    ],
  },
  'beas-kund': {
    trekId: 'beas-kund',
    waypoints: [
      { day: 1, locationKey: 'manali', kind: 'start', activity: 'drive' },
      { day: 2, locationKey: 'beas-kund', kind: 'water', activity: 'trek' },
      { day: 3, locationKey: 'manali', kind: 'end', activity: 'trek' },
    ],
  },
  'yulla-kanda': {
    trekId: 'yulla-kanda',
    waypoints: [
      { day: 1, locationKey: 'dehradun-railway', kind: 'start', activity: 'drive' },
      { day: 3, locationKey: 'yulla-kanda', kind: 'summit', activity: 'summit' },
      { day: 5, locationKey: 'dehradun-railway', kind: 'end', activity: 'drive' },
    ],
  },
  'buran-ghati': {
    trekId: 'buran-ghati',
    waypoints: [
      { day: 1, locationKey: 'dehradun-railway', kind: 'start', activity: 'drive' },
      { day: 4, locationKey: 'buran-ghati', kind: 'pass', activity: 'summit' },
      { day: 6, locationKey: 'dehradun-railway', kind: 'end', activity: 'drive' },
    ],
  },
  'bhrigu-lake': {
    trekId: 'bhrigu-lake',
    waypoints: [
      { day: 1, locationKey: 'manali', kind: 'start', activity: 'drive' },
      { day: 2, locationKey: 'bhrigu-lake', kind: 'water', activity: 'trek' },
      { day: 3, locationKey: 'manali', kind: 'end', activity: 'trek' },
    ],
  },
  'kheerganga': {
    trekId: 'kheerganga',
    waypoints: [
      { day: 1, locationKey: 'kasol', kind: 'start', activity: 'rest' },
      { day: 2, locationKey: 'kasol', kind: 'end', activity: 'trek' },
    ],
  },
  'do-dham': {
    trekId: 'do-dham',
    waypoints: [
      { day: 1, locationKey: 'rishikesh', kind: 'start', activity: 'drive' },
      { day: 3, locationKey: 'kedarnath', kind: 'temple', activity: 'trek' },
      { day: 5, locationKey: 'badrinath', kind: 'temple', activity: 'drive' },
      { day: 7, locationKey: 'rishikesh', kind: 'end', activity: 'drive' },
    ],
  },
  'char-dham': {
    trekId: 'char-dham',
    waypoints: [
      { day: 1, locationKey: 'rishikesh', kind: 'start', activity: 'drive' },
      { day: 4, locationKey: 'kedarnath', kind: 'temple', activity: 'trek' },
      { day: 7, locationKey: 'badrinath', kind: 'temple', activity: 'drive' },
      { day: 10, locationKey: 'rishikesh', kind: 'end', activity: 'drive' },
    ],
  },
  'panch-kedar': {
    trekId: 'panch-kedar',
    waypoints: [
      { day: 1, locationKey: 'rishikesh', kind: 'start', activity: 'drive' },
      { day: 5, locationKey: 'kedarnath', kind: 'temple', activity: 'trek' },
      { day: 10, locationKey: 'rishikesh', kind: 'end', activity: 'drive' },
    ],
  },
  'nepal-backpacking': {
    trekId: 'nepal-backpacking',
    waypoints: [
      { day: 1, locationKey: 'kathmandu', kind: 'start', activity: 'rest' },
      { day: 3, locationKey: 'pokhara', kind: 'village', activity: 'drive' },
      { day: 7, locationKey: 'kathmandu', kind: 'end', activity: 'drive' },
    ],
  },
  'kathmandu-tour': {
    trekId: 'kathmandu-tour',
    waypoints: [{ day: 1, locationKey: 'kathmandu', kind: 'start', activity: 'rest' }],
  },
  'pokhara-tour': {
    trekId: 'pokhara-tour',
    waypoints: [{ day: 1, locationKey: 'pokhara', kind: 'start', activity: 'rest' }],
  },
  'chitwan-safari': {
    trekId: 'chitwan-safari',
    waypoints: [
      { day: 1, locationKey: 'kathmandu', kind: 'start', activity: 'drive' },
      { day: 2, locationKey: 'chitwan', kind: 'viewpoint', activity: 'drive' },
      { day: 4, locationKey: 'kathmandu', kind: 'end', activity: 'drive' },
    ],
  },
};
